.github/workflows/build.yml
This will add a build test in ubuntu 18.04 to validate that no changes have broken the build. This should allow for easy expanding to more OS by just adding more lines to the include section on line 19, and adding their method for installing dependencies if apt is not applicable. This is set to run on both push and pull requests.
Closes #16
=> Github Action ubuntu build

README.md
The link to the slack instance is slightly mis-formatted, this fixes it
=> Fixes link to slack instance

truenas_install/__main__.py
The truenas SCALE installer was failing in part because of this code when installing to an nvme disk. I updated the code to check if nvme or non-nvme and use the correct naming convention accordingly.
=> Add nvme detection

.github/workflows/build.yml
This is nice to have for testing out ISOs built from pull requests, etc. The build system did all that work creating the ISO file, why build it again locally to test it?
=> Upload the ISO Files from CI Runs

conf/build.manifest
This is required for ethernet to function on many Dell servers, including my R710
=> Add firmware-bnx2 package to TrueNAS build

.github/workflows/build.yml
In my commit yesterday I didn't notice that the clean step deletes the ISO right before it can be uploaded. This minor PR moves the clean step to after the ISO is uploaded.
=> Change Step Order to Fix ISO Upload

conf/build.manifest
This commit removes dependencies field from the manifest as it's only a source of confusion and has no real purpose.
=> Clean build manifest

truenas_install/__main__.py
@william-gr I've made a mistake, let's discard freenas repo PR, this is a better approach that requires no 12 backport (i.e. will allow updates from already released 12.0-U1)
=> Fix 12 to SCALE upgrade

scripts/build.sh
Build server doesn't have this file so it's a broken symlink which means the `if [ -e ]` check is never successful. Just remove the file instead of checking.
=> NAS-108761 / 21.02 / dont check for nvidia.conf (its a symlink), just remove file

conf/build.manifest
We are seeing an issue after recent update of debian packages where aiohttp does not parse the URI correctly - however this is not reproducible on aiohttp 3.7.3 version which is the latest available and debian upstream just tagged it but it isn't available yet.
=> Update aiohttp version

.gitignore, conf/build.manifest, scripts/build.sh
anytime we want to force downstream builders to perform a full rebuild
and invalidate any local incremental cache.
=> Add support for build epoch counter. This allows us to bump the number

conf/build.manifest
Add utilities to manipulate Samba-style XDR-formatted NFSv41 ACLs. Package is modified version nfs4-acl-tools to support the xattr format and newer NFSv4 spec. NFSv41 style auto-inheritance is not yet implemented.
=> Add nfs4xdr-acl-tools to build

conf/build.manifest
This PR adds changes to remove repos from build because some of them are not required anymore and some already have changed upstream to the version we desire so it's not necessary to maintain a fork or build them each time.
=> Remove repositories from build

conf/build.manifest
Adds the dnsutils package, as requested in NAS-109391 and  here:
https://www.truenas.com/community/threads/new-suggestion-add-nslookup-and-or-dig.91041/
**Reasoning behind change:**
dnsutils comes in handy when people run into issues with dns and/or networking in general.
Which actually what a significant amount of issues reported on the forums is about.
Signed-off-by: Kjeld Schouten-Lebbing <kjeld@schouten-lebbing.nl>
=> NAS-109391 / 21.04 / Add dnsutils package

conf/build.manifest
After openzfs changes, we would like to have a clean rebuild of packages dependent on openzfs, bumping build-epoch will have the desired affect.
=> Bump build epoch to force a clean rebuild

conf/build.manifest, scripts/build.sh, scripts/functions.sh
This adds linux kernel to the build. Due to size of repo and temporary files,
logic for building kernel is slightly different than other packages. A non-tmpfs
filesystem is overlaid as dpkg-src in this case and build on it rather than tmpfs.
Kernel config is generated in two or three steps during the build process.
make defconfig is run to generate a default config based on architecture, then
the TrueNAS-specific configuration is merged with it, and if a debug kernel is
requested (by uncommenting relevent line in build.sh), additional debugging parameters
are applied.
A customized copy of current kernel source is also mounted as /kernel inside the
package build chroot. A new key has also been added to the build_manifest "kernel_module",
which if set to true will cause the kernel image and …
=> Build with custom kernel

conf/build.manifest
OpenZFS uses alien to build the debs, but Debian has a bug in their
alien version 8.95.3 that causes the generated rules to be incorrect.
Work around this for the time being with a local version of the alien
package.  This has been named alienz to make sure we are using the
local version rather than the upstream package.
https://salsa.debian.org/debian/alien/-/merge_requests/2
=> Work around broken alien package

scripts/build.sh
This commit adds changes to not use overlay mount for building kernel package as this means that this won't build on zfs ( https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1873917 ) because we are unable to mount.
=> Do not use overlay mount

conf/build.manifest
Adding to base packages since this tool will be used heavily when NVMe "functionality" is added to SCALE Enterprise.
=> NAS-110344 / 21.06 / add nvme-cli to base packages

scale_build/image/iso.py
This commit adds change to set hostname of TN installer so that it does not advertise the hostname of the builder.
=> NAS-110343 / 21.06 / Update hostname for TN installer

truenas_install/__main__.py
This commit fixes an issue where if upgrade process failed for some reason, bootfs property would be unset because the new BE dataset would be destroyed. This resulted in zectl to not consider the system to be configured for boot environments.
=> Set bootfs property in case of an exception

conf/build.manifest
NOTE: Depends on truenas/zfs-2.1-release branch for samba, libzfs, and zectl.
=> Switch to OpenZFS 2.1

conf/build.manifest
This commit adds changes to remove alienz from build manifest as it's no longer required with upstream having required fixes.
=> Remove alienz from build manifest

conf/build.manifest
This commit adds changes to remove python3-aiohttp remove from build manifest as we have an updated version available upstream now which was not the case when it was added to build.
=> Remove python3-aiohttp from build manifest

conf/cd-files/root/.bash_profile
The install script exits with an error when the user cancels.  We should
restart the installer rather than dropping to a shell.
=> NAS-110812 / 21.08 / Restart truenas-install on failure

conf/build.manifest
This PR adds changes to build inadyn from source as the package has not been maintained since mid 2010s in debian repository and we are outdated.
=> NAS-110826 / 21.08 / Build inadyn from source

conf/build.manifest, scale_build/packages/build.py, scale_build/packages/package.py
This commit adds changes to allow specifying enviornment variables independently for each package. This is helpful to avoid influence of one env variable meant for a specific package on another which might result in changed behavior when it builds.
=> NAS-110934 / 21.08 / Allow specifying environment variables independently

Makefile
This commit adds changes to re-install scale-build in virtualenv if there are manual edits, this is very helpful for devs during debugging where they don't have to manually remove virtual env.
=> NAS-111272 / 21.08 / Re-install scale-build if there are manual edits

conf/build.manifest
`python2` is being installed on SCALE by upstream Debian. See https://packages.debian.org/sid/main/python-is-python2 for details. We already ensure all the dependent ports (and the ones we write) use python3 so no need to keep this around.
However, I'm explicitly installing the `python-is-python3` package since it, literally, only creates a symlink to `/bin/python`. It would be incredibly time consuming to track every single 3rd party package/script  that references the `python` binary file so this should keep the unforeseen fall-out minimal.
=> NAS-111358 / 21.08 / remove python-is-python2 package

truenas_install/__main__.py
This commit adds changes to ensure bootloader property is set for BE's so that zectl is able to consume our grub plugin to update grub after making changes to boot environments.
=> NAS-110816 / 21.08 / Set bootloader property so zectl can update grub

conf/build.manifest
Fix multiple problems:
1. `make dpkg` was being run as a `prebuildcmd` but that command actually built the package. So in `_build_impl()` we ran `debuild` which also builds the packages after any `prebuildcmd`. This means we were building `scst` twice...
2. Upstream has fixed multiple issues with the debian packaging, so take advantage of those  fixes
3. I've condensed the divergence from upstream to only making minor modifications to `scst/Makefile`.
4. Finally, `truenas-svn-trunk` is rebased on latest upstream `svn-trunk` which brings in a fix where `zvol` resize was not working without manually restarting the service.
=> NAS-111865 / 21.10 / update scst and fix the build

scale_build/image/iso.py
This commit adds changes to make sure we provide custom built packages to the iso chroot env so that they are prioritized over upstream packages.
=> NAS-113283 / 22.02-RC.2 / Provide iso chroot env with custom built packages

conf/build.manifest
This commit adds changes to build our own custom version of waagent as upstream waagent debian package is outdated resulting in python39 compatibility issues.
=> NAS-112773 / 22.02-RC.2 / Add waagent to build manifest

conf/build.manifest
`zstd` brings in `unzstd` which allows uncompressing core dump files on SCALE (they're compressed using zstd algorithm by default).
=> NAS-113855 / 22.02 / add zstd to SCALE

truenas_install/__main__.py
This commit adds changes to not enable waagent automatically as we are unable to tell the difference between pure hyper-v and azure based vms.
=> NAS-114226 / 22.02 / Do not enable waagent automatically

conf/build.manifest
We want to install waagent before truenas as waagent is not disabled otherwise because it's not installed at the time. So we will be adding waagent as a dependency for truenas.
=> Have waagent install as a dep for truenas

truenas_install/__main__.py
This file may have outdated info in it. Worst case scenario, user ends up with some unexpectedly enabled services.
=> Failing to enable services from our JSON file should not be fatal

conf/build.manifest
This is primarily intended for use on regression tests through
local NFS mounts, but may also be of some use to support or
sys admins.
=> Add nfs4-acl-tools to the base install

conf/build.manifest
git cherry-pick -x b9f9cfd25c7df862f08b30a39ab263e8e5e27792
git cherry-pick -x 6eaacb40ba19d63e0d6490c61e2db49c5fd5f4b0
Powertop is a vital Intel-provided tool for monitoring per-process powerconsumption on power-efficiency focussed systems.
It also allows access to some intel-adviced optimalisations, which is, ofcoarse, not actively supported.
Ofcoarse it does not enable any running-by-default services and also does not make any system changes by default either. Unless manually enabled by the user to do so.
It has to be noted that users of more power-optimised NAS systems are one of the side audiences that SCALE appeals to (as the linux kernel is generally more power efficient), adding this also …
=> NAS-113898 / 22.02 / Add PowerTop to SCALE (by Ornias1993)

truenas_install/__main__.py
…ions recursively because it can contain snapshots
Original PR: https://github.com/truenas/scale-build/pull/245
Jira URL: https://jira.ixsystems.com/browse/NAS-115069
=> NAS-115069 / 22.02.1 / Destroy old `boot-pool/grub` dataset when upgrading FreeBSD installat… (by themylogin)

scale_build/bootstrap/bootstrapdir.py
This commit fixes an issue where we were not adding our custom apt mirrors before installing some basic packages like build-essential etc. Problem was that these packages pull in packages like openssl which we want to pull from specific apt mirror based on our apt preferences rather then using whatever is being provided with the default apt mirrors from debootstrap.
=> NAS-115391 / 22.12 / Add apt mirrors before fetching packages

conf/build.manifest
Previously for TrueNAS, Debian Linux kernel configuration was used and
TrueNAS config options were added on top of that. Because of that,
TrueNAS kernel config in 'scripts/package/truenas/tn.config' has grown
very large and difficult to manage for TrueNAS only options.
Debian Linux kernel configuration for version 5.10.92 has been added
as 'debian_amd64.config' to keep the options from Debian seperate from
TrueNAS options. TrueNAS only config options are stored in
'truenas.config'.
Signed-off-by: Umer Saleem <usaleem@ixsystems.com>
=> NAS-114235 / 22.12 / Better Linux kernel configuration procedure

scale_build/checkout.py, scale_build/packages/package.py
Parallelize the git checkout of repos. This greatly reduces the time needed to checkout the repos since it's currently being done synchronously. The major outlier is the `github.com/truenas/linux` repo for obvious reasons, but now all the other repos will be checked out without having to wait for that one to finish.
=> NAS-115468 / 22.12 / parallelize the git checkout of repo sources

scale_build/packages/git.py
Once a package has completed checkout, we are not printing another statement showing that the package's checkout process is complete as otherwise with packages being checkout in parallel, it reduces visibility as to what is still active and what isn't.
=> Improve logging when checking out

README.md
I tried to do `make packages` and it crashed because `rsync` wasn't installed even though I simply copied and pasted the `apt install` command from the `README.md` 😄 
Add it to the `README.md` so lazy people like myself can copy and paste.
=> NAS-115606 / 22.12 / add rsync to depends in README.md

conf/build.manifest
K3s now wants to use at least golang 1.17 for building.
=> NAS-115585 / 22.12 / Use golang 1.17 for building k3s

conf/sources.list
We have a ticket to dynamically render this, until we have that fix - correcting the sources for now.
=> NAS-115622 / 22.12 / Fix apt sources

conf/build.manifest
SCST changed upstream locations and this repo has been changed to reflect that. This means our very minor patches to make this build were lost (as expected).
The good news is that we no longer to need to maintain a set of local patches, we can build directly from upstream using the patches in this PR.
=> NAS-115250 / 22.02.1 / SCST changed upstream locations and fix build

conf/build.manifest
SCST changed upstream locations and this repo has been changed to reflect that. This means our very minor patches to make this build were lost (as expected).
The good news is that we no longer to need to maintain a set of local patches, we can build directly from upstream using the patches in this PR.
Original PR: https://github.com/truenas/scale-build/pull/273
Jira URL: https://jira.ixsystems.com/browse/NAS-115250
=> NAS-115250 / 22.12 / SCST changed upstream locations and fix build (by yocalebo)

README.md
I tried to do `make packages` and it crashed because `rsync` wasn't installed even though I simply copied and pasted the `apt install` command from the `README.md` 😄 
Add it to the `README.md` so lazy people like myself can copy and paste.
Original PR: https://github.com/truenas/scale-build/pull/267
Jira URL: https://jira.ixsystems.com/browse/NAS-115606
=> NAS-115606 / 22.02.1 / add rsync to depends in README.md (by yocalebo)

scale_build/packages/git.py
It'd be nice to log to the branch that's being checked out/updated during the git checkout phase.
Original PR: https://github.com/truenas/scale-build/pull/275
Jira URL: https://jira.ixsystems.com/browse/NAS-115647
=> NAS-115647 / 22.02.1 / Log branch override (by yocalebo)

scale_build/config.py
I'm trying to work on some other tickets and I got a message to set `SKIP_SOURCE_REPO_VALIDATION` so I did `export SKIP_SOURCE_REPO_VALIDATION=y`
Tried to do `make packages` and it crashed with `ValueError` because we're trying to cast the result to `int`
With these changes, I've added a `get_env_variable` function that properly sets the environment variables in a programmatic way that should, hopefully, prevent these types of crashes in the future.
=> NAS-115605 / 22.12 / Fix ValueError crashes

scale_build/config.py
I'm trying to work on some other tickets and I got a message to set `SKIP_SOURCE_REPO_VALIDATION` so I did `export SKIP_SOURCE_REPO_VALIDATION=y`
Tried to do `make packages` and it crashed with `ValueError` because we're trying to cast the result to `int`
With these changes, I've added a `get_env_variable` function that properly sets the environment variables in a programmatic way that should, hopefully, prevent these types of crashes in the future.
Original PR: https://github.com/truenas/scale-build/pull/266
Jira URL: https://jira.ixsystems.com/browse/NAS-115605
=> NAS-115605 / 22.02.1 / Fix ValueError crashes (by yocalebo)

conf/build.manifest, scale_build/bootstrap/bootstrapdir.py
This PR addresses following issues:
1. Backport bluefin fixes where we were not configuring mirrors before installing some base packages
2. Address CVE's in packages for angelfish
=> NAS-115645 / 22.02.1 / Address CVE's in packages for angelfish

conf/build.manifest
Previously for TrueNAS, Debian Linux kernel configuration was used and
TrueNAS config options were added on top of that. Because of that,
TrueNAS kernel config in 'scripts/package/truenas/tn.config' has grown
very large and difficult to manage for TrueNAS only options.
Debian Linux kernel configuration for version 5.10.92 has been added
as 'debian_amd64.config' to keep the options from Debian seperate from
TrueNAS options. TrueNAS only config options are stored in
'truenas.config'.
Signed-off-by: Umer Saleem <usaleem@ixsystems.com>
=> NAS-114235 / 22.02.2 / Better Linux kernel configuration procedure

conf/build.manifest, scale_build/bootstrap/bootstrapdir.py
This PR fixes an issue where we ensure that the packages in the bootstrapped dir are actually what we want wrt apt preferences defined.
=> NAS-115939 / 22.12 / Upgrade debian packages pulled in by debootstrap

conf/build.manifest, scale_build/bootstrap/bootstrapdir.py
This PR fixes an issue where we ensure that the packages in the bootstrapped dir are actually what we want wrt apt preferences defined.
Original PR: https://github.com/truenas/scale-build/pull/292
Jira URL: https://jira.ixsystems.com/browse/NAS-115939
=> NAS-115939 / 22.02.1 / Upgrade debian packages pulled in by debootstrap (by sonicaj)

conf/build.manifest, scale_build/bootstrap/bootstrapdir.py
This PR fixes an issue where we ensure that the packages in the bootstrapped dir are actually what we want wrt apt preferences defined.
Original PR: https://github.com/truenas/scale-build/pull/292
Jira URL: https://jira.ixsystems.com/browse/NAS-115939
=> NAS-115939 / 22.02.2 / Upgrade debian packages pulled in by debootstrap (by sonicaj)

scale_build/packages/git.py
Our SCALE VM builders are failing to checkout git repos. The repo it fails on and when it fails are completely random. Until the root cause can be diagnosed and subsequently fixed, this will retry the update or checkout phase if a failure is encountered.
I've updated the logging verbiage so that we know when a retry is taking place.
=> NAS-116170 / 22.12 / retry git commands on failure

scale_build/packages/git.py
Our SCALE VM builders are failing to checkout git repos. The repo it fails on and when it fails are completely random. Until the root cause can be diagnosed and subsequently fixed, this will retry the update or checkout phase if a failure is encountered.
I've updated the logging verbiage so that we know when a retry is taking place.
Original PR: https://github.com/truenas/scale-build/pull/298
Jira URL: https://jira.ixsystems.com/browse/NAS-116170
=> NAS-116170 / 22.02.2 / retry git commands on failure (by yocalebo)

truenas_install/__main__.py
Currently, grub-install only creates one EFI boot entry for one boot
disk. If that boot disk gets compromised, system cannot boot from any
other disk since the boot entry is not present. Creating boot entries
for all boot disks fixes this issue.
=> NAS-115611 / 22.12 / NAS-115611: Create EFI boot entries for all boot disks

conf/build.manifest
git cherry-pick -x 4f6fbf159c3bb65b6d2c1c515b40a1effdd53665
Original PR: https://github.com/truenas/scale-build/pull/306
Jira URL: https://jira.ixsystems.com/browse/NAS-116030
=> NAS-116030 / 22.02.2 / Remove `truenas-devel` package (by themylogin)

conf/build.manifest
The new branch name was chosen for consistency with other truenas repo
conventions.
=> NAS-116844 / 22.12 / Update branch name for linux to truenas/linux-5.15

scale_build/image/manifest.py
It was requested that we add size of the update file to the build manifest so that it can be used interactively by UI to determine if we have enough space to download the update file.
Original PR: https://github.com/truenas/scale-build/pull/311
Jira URL: https://jira.ixsystems.com/browse/NAS-116685
=> NAS-116685 / 22.02.3 / Add update file size to manifest (by Qubad786)

scale_build/config.py
```
File "/usr/lib/python3/dist-packages/middlewared/plugins/update_/install_linux.py", line 43, in _install
raise CallError(f'Unable to downgrade from {old_version} to {new_version}')
middlewared.service_exception.CallError: [EFAULT] Unable to downgrade from 22.02.2.1 to 22.02.2-MASTER-20220713-041129
```
=> NAS-117170 / 22.02.3 / bump version to 22.02.3

.gitignore, conf/build.manifest, scale_build/config.py, scale_build/packages/git.py, scale_build/packages/package.py, scale_build/packages/utils.py, scale_build/utils/manifest.py, scale_build/utils/package.py
This PR introduces following changes:
1. Conditional builds of sources
2. Allowing ssh based origin of sources
3. Integrating corssl in TrueNAS for FIPS compliance
4. Various minor bug fixes and enhancements in the builder
Motivation behind the above changes is to basically allow building a separate version of TrueNAS SCALE which is FIPS compliant using CorSSL.
For consumers wishing to build FIPS compliant SCALE, they can set the env variable `FIPS=1` when checking out / building packages. Usage would look something like the following:
```
env corssl_OVERRIDE_IDENTITY_FILE_PATH=identities/key FIPS=1 sh -c "make checkout && make packages"
```
`corssl_OVERRIDE_IDENTITY_FILE_PATH` env variable is provided in order for `checkout` to succeed as `corssl` uses SSH based origin and an identity …
=> NAS-117519 / 22.12 / Various improvements to builder

conf/reference-files/etc/group
It was requested that we add a `wheel` group to help users migrating from CORE to SCALE making sure their workflow is not affected as in SCALE the group with same uid is known as `root` instead of `wheel`.
=> NAS-116521 / 22.12 / Add wheel group

truenas_install/__main__.py
This commit adds changes to move setting password and updating some other configuration bits when proc is mounted as when corssl is used, it uses a library which requires proc to be available in order to determine which module is being used.
=> NAS-117723 / 22.12 / Crypto related libraries should be used when proc is mounted

conf/build.manifest
Those tools are mostly targeted to Intel Optane/DCPMM, especially the second, but some people may find them useful.
=> NAS-108490 / 22.12 / Add ndctl and ipmctl packages to manage NVDIMMs.

conf/build.manifest
This PR adds changes to bring in newer nvidia mirror to install 515* nvidia packages instead of 470 ones which are considered legacy now. Also fix other issues which we are running into after updating apt mirrors.
=> NAS-117696 / 22.12 / Fix build after getting newer apt mirrors

scale_build/update_image.py
This commit fixes an issue where if we raise exception in reference files checks, chroot mounts are not properly cleaned up and we try to nuke the directory which results in builder removing already built packages.
=> NAS-117776 / 22.12 / Clean chroot mounts when making update image

conf/build.manifest
We should be clear to switch to regular upstream debian package for this. For background see associated middleware PR.
=> NAS-117840 / 22.12 / Remove customized nss-pam-ldap from build

truenas_install/__main__.py
It was requested that we set `600` permissions for database file to avoid it being world readable.
=> NAS-117759 / 22.12 / Set 0o700 permissions for data directory

scale_build/image/iso.py
Joe should be discussing this PR with Waqar.
This will allow us to automate the shasum checking in our jenkins pipline since the shasum file will now be made so that we can use `shasum -c ` to verify its correct once the push has happened.
=> NAS-118141 / 22.12 / allow easy checking of sha256 checksum

conf/build.manifest, conf/sources.list
This commit removes redundant security mirror we added for 22.02.3 as this time we have updated the security mirror we have for angelfish.
=> NAS-118239 / 22.02.4 / Remove redundant debian-security mirror

conf/build.manifest
These tools may be useful for diagnosing mDNS issues in field as well as doing CI.
=> NAS-118500 / 22.12 / Include avahi-utils in the build

conf/build.manifest
This PR adds changes to always prioritize local built packages first before checking upstream mirrors for them.
=> NAS-116543 / 22.12 / Update apt preferences to always prioritize local built packages first

conf/build.manifest
These are used by CTDB mutex helper script to maintain cluster recovery lock.
=> NAS-118134 / 22.12 / Add libgfapi python bindings for build

conf/build.manifest
This causes us to ship kernel objects (specifically the nvidia dkms related packages) that have been built against an incorrect kernel version that SCALE does not run.
=> NAS-118856 / 22.12 / remove incorrect headers package

conf/build.manifest
This causes us to ship kernel objects (specifically the nvidia dkms related packages) that have been built against an incorrect kernel version that SCALE does not run.
Original PR: https://github.com/truenas/scale-build/pull/354
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118856
=> NAS-118856 / 22.12-RC.1 / remove incorrect headers package (by yocalebo)

conf/build.manifest
Upstream version is too naive in reporting "health_state".  This should be more consistent with specs within limitations of ndctl internal APIs, based on Intel DCPMM/Optane.
=> NAS-113872 / 22.12 / Patch ndctl to improve NVDIMM health monitoring.

scale_build/main.py
Fix exclusive action, the related commit is https://github.com/truenas/scale-build/commit/f1b38c78bb01cf3e065327ed9b81e3782701486e.
Before the fix:
ArgParser print help messages between commands `scale_build checkout` and `scale_build packages`
After the fix:
No help messages anymore.
=> NAS-119312 / 23.10 / fix exclusive action condition

conf/build.manifest
This gives administrator ability to convert character encoding types for file names. This can be a  matter of last resort for normalizing file names in ways that are compatible across all clients.
=> NAS-119315 / 23.10 / Add convmv package to base install

conf/build.manifest
This gives administrator ability to convert character encoding types for file names. This can be a  matter of last resort for normalizing file names in ways that are compatible across all clients.
Original PR: https://github.com/truenas/scale-build/pull/368
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119315
=> NAS-119315 / 22.12.1 / Add convmv package to base install (by anodos325)

conf/build.manifest
Native Debian is integrated with TrueNAS ZFS. This commit updates the OpenZFS build process to use native Debian packaging for SCALE.
I have built and tested SCALE installation/update with this change set applied. I have not seen any issue so far.
This PR should be merged after https://github.com/truenas/zfs/pull/111 is merged.
=> NAS-116639 / 23.10 / Build OpenZFS with native Debian packaging

conf/build.manifest
Upstream SCST has finally branched for their 3.7 branch which means it's become "stable".
I've created a `truenas-3.7.x` branch that is based off upstream `3.7.x` branch.
=> NAS-119820 / 23.10 / build SCST off upstream stable 3.7.x branch

conf/reference-files/etc/group
i2c-tools creates a new local user `i2c`.
Original PR: https://github.com/truenas/scale-build/pull/391
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121239
=> NAS-121239 / 22.12.3 / fix build (by yocalebo)

conf/build.manifest
This adds the ndctl proper package. Since Cobia is based off bookworm, this pulls in a new upstream version which includes Mav's many fixes.
=> NAS-121450 / 23.10 / add ndctl proper package

conf/build.manifest
This is being removed in Cobia since our fork hasn't been updated in 3 years but even more so, we are no longer using it in middleware repo. See https://github.com/truenas/middleware/pull/11109 for details.
=> NAS-121477 / 23.10 / remove unused repo

conf/build.manifest
In order to integrate ixdiagnose to middleware we need to add it to scale build so it's debian package (PR up for ixdiagnose debian package https://github.com/truenas/ixdiagnose/pull/15) can then be consumed by middlewared debian package build.
=> NAS-121556 / 23.10 / Add ixdiagnose to build

conf/build.manifest
This package is for dealing with smart cards. More importantly, however, is that it has active CVE vulnerabilities that need to be patched. This is brought in via the `easy-rsa` package which is brought in via the `openvpn` service. We, obviously, can't remove openvpn but we can safely remove opensc.
=> NAS-121733 / 23.10 / remove opensc from base image

conf/build.manifest
This package is for dealing with smart cards. More importantly, however, is that it has active CVE vulnerabilities that need to be patched. This is brought in via the `easy-rsa` package which is brought in via the `openvpn` service. We, obviously, can't remove openvpn but we can safely remove opensc.
Original PR: https://github.com/truenas/scale-build/pull/404
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121733
=> NAS-121733 / 22.12.3 / remove opensc from base image (by yocalebo)

conf/build.manifest
I'm chasing API test failures in jenkins and it seems to be related to incremental caching certain packages that need to be rebuilt. Bump the build-epoch so that we force a clean build everywhere. This is probably better to do anyways, since we're mostly done with the massive changes related to bookworm transition.
=> NAS-121767 / 23.10 / bump build-epoch to force clean build

conf/build.manifest, scale_build/packages/build.py, scale_build/packages/package.py, scale_build/tests/unit/test_package_rebuild_logic.py, scale_build/utils/manifest.py
This PR adds changes to remove kernel module flag as it was introduced to handle the cases where linux kernel headers debian package's name changed each time there were changes in kernel headers which meant that relevant repositories needed to be updated to reflect that change.
However with recent truenas kernel changes, those names are now static and we can properly specify build/install time dependencies instead of injecting these dependencies in the build/install environment which means that the whole process now goes throught apt and is handled like any other package.
=> NAS-121888 / 23.10 / Remove kernel module flag from builder

scale_build/image/update.py
We already remove the execute bit on the apt* related binaries, but those are simply a wrapper around dpkg. We need to remove execute bit on dpkg since it is the binary that's actually responsible for installing the binary.
Original PR: https://github.com/truenas/scale-build/pull/418
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121741
=> NAS-121741 / 22.12.3 / remove execute bit on dpkg binary (by yocalebo)

conf/build.manifest
Mention production kernel image and headers for OpenZFS Build-Depends. Mention debug kernel image and headers for OpenZFS Build-Depends.
=> NAS-121915 / Update Build-Depends for OpenZFS debian/control

conf/build.manifest
Also include `open-iscsi` (for use by HA standby node).
=> NAS-119337 / 23.10 / Use truenas-pre-3.8.x scst branch

conf/build.manifest
This PR adds support to build and install perf package for TrueNAS SCALE kernel.
This PR should be merge after the respective PR in Linux kernel repo is merged: https://github.com/truenas/linux/pull/94
=> NAS-121339 / 23.10 / Build perf for TrueNAS kernel

truenas_install/__main__.py
Python modules imported within the truenas-initrd.py script may link against libs that are only present in the squashfs dir and so we should make ld aware of the usr/lib dir within it since we're not chrooted.
=> NAS-122119 / 22.12.3 / use LD_LIBRARY_PATH when installing / upgrading

conf/build.manifest
sgdisk does not allow to set pmbr_boot flag.
For context: https://github.com/truenas/truenas-installer/pull/61
=> NAS-120382 / 23.10 / Add parted tool in installer image to set PMBR boot flag

conf/build.manifest, scale_build/image/update.py, scale_build/utils/manifest.py
This PR adds changes to allow us to not install recommended packages of some package. Right now we default to assuming that each package wants recommended packages to be installed however we can move ahead with the pruning slowly and have a default where recommended packages are not brought in by default and only in some cases where it is required we can bring those in.
We also fix truecommand here as it is not functional atm because of `wireguard-tools` package missing and if we install its recommended packages it brings in `wireguard-dkms` which we don't want as then it starts pulling upstream linux kernel headers.
=> NAS-121623 / 23.10 / Allow not installing recommended packages of a package

conf/build.manifest
This reverts commit ff30d75257afba7c4589c25c049b3151e05a1805.
=> NAS-122361 / 23.10 / Revert "Bring back upstream gluster mirror"

conf/build.manifest
Prior to this change the `2debug` was **not** taking effect:
```
root@scale1[~]# uname -a
Linux scale1 6.1.24-debug+truenas #2 SMP PREEMPT_DYNAMIC Wed Jun  7 23:04:50 UTC 2023 x86_64 GNU/Linux
root@scale1[~]# cat /sys/kernel/scst_tgt/version
3.8.0-pre (revision=)
TRACING
root@scale1[~]# echo all > /sys/kernel/scst_tgt/trace_level
root@scale1[~]# dmesg
[ 2090.661357] [6401]: scst: scst_write_trace:304:Changed trace level for "scst": old 0x00002508, new 0xffffffff
root@scale1[~]# cat /sys/kernel/scst_tgt/version
3.8.0-pre (revision=)
TRACING
root@scale1[~]# dmesg
[ 2090.661357] [6401]: scst: scst_write_trace:304:Changed trace level for "scst": old 0x00002508, new 0xffffffff
root@scale1[~]#
```
(note the absence of DEBUG in _/sys/kernel/scst_tgt/version_)
With this change, it does:
``` …
```
=> NAS-121173 / 23.10 / Use 2debug when building scst-dbg

conf/reference-files/etc/group, conf/reference-files/etc/passwd
Netdata user/group if not added to reference files results in build failing.
Update user/group reference files so that they correctly reflect the netdata user/group and this results in persistent uid/gid for netdata user in scale.
=> NAS-119538 / 23.10 / Add netdata user/group

conf/build.manifest
Like the comment states, I'm adding this package here specifying "install_recommends: false" so we don't install a bunch of non-sense into our base image.
=> NAS-123016 / 23.10 / fix apps in Cobia

requirements.txt, truenas_install/__main__.py
This reverts commit 0b7cf5806976e94fb105613537f196598c37a5f6.
Unfortunately, for reasons not understood, this is causing `truenas-initrd.py` in the upgrade image to core dump. Reverting this commit fixes the issue. There will be a subsequent commit to fix the issue this tried to fix in the first place. (Failing to import libraries on fresh install)
=> NAS-123275 / 23.10 / Revert "NAS-122119 / use LD_LIBRARY_PATH when installing / upgrading

Makefile
This commit adds a fix which makes sure the makefile is able to setup virtualenv for scale builder execution as stable debian release now does not allow setting it up unless user explicitly specifies it.
=> NAS-123615 / 24.04 / Fix makefile not able to setup virtualenv

Makefile
This commit adds a fix which makes sure the makefile is able to setup virtualenv for scale builder execution as stable debian release now does not allow setting it up unless user explicitly specifies it.
Original PR: https://github.com/truenas/scale-build/pull/483
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123615
=> NAS-123615 / 23.10 / Fix makefile not able to setup virtualenv (by sonicaj)

Makefile
This commit adds changes to be backwards compatible with older bullseye builders where pip does not yet support break system packages flag.
=> NAS-123630 / 24.04 / Check if pip supports break systeem packages flag

Makefile
This commit adds changes to be backwards compatible with older bullseye builders where pip does not yet support break system packages flag.
Original PR: https://github.com/truenas/scale-build/pull/485
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123630
=> NAS-123630 / 23.10 / Check if pip supports break systeem packages flag (by sonicaj)

Makefile
git cherry-pick -x 36afbd5847e1f21e01d80b0ddf3b9525edb616a3
git cherry-pick -x 0b4bff0c0eee60d0b3eea3ff5ac71cc796fd5099
This commit adds a fix which makes sure the makefile is able to setup virtualenv for scale builder execution as stable debian release now does not allow setting it up unless user explicitly specifies it.
Original PR: https://github.com/truenas/scale-build/pull/483
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123615
Original PR: https://github.com/truenas/scale-build/pull/484
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123615
=> NAS-123615 / 22.12.4 / Fix makefile not able to setup virtualenv (by sonicaj) (by bugclerk)

Makefile
This commit adds changes to be backwards compatible with older bullseye builders where pip does not yet support break system packages flag.
Original PR: https://github.com/truenas/scale-build/pull/485
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123630
Original PR: https://github.com/truenas/scale-build/pull/486
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123630
=> NAS-123630 / 22.12.4 / Check if pip supports break systeem packages flag (by sonicaj) (by bugclerk)

scale_build/image/update.py, scale_build/main.py, scale_build/validate.py, truenas_install/__main__.py, truenas_install/fhs.py
Create filesystem hierarchy for new boot environments based
on specifications in fhs.py file in truenas_install directory.
This gives us more flexibility regarding which parts of FS to
make readonly, and also identifying precise local changes from
a pristine environment that users have made to system files.
Precise settings detailed in comments in the specification file.
Overall, this gives better posture for STIG compliance regarding
auditability and prevention of unauthorized OS changes.
=> NAS-124055 / 24.04 / Implement dataset-based filesystem hierarchy

truenas_install/__main__.py, truenas_install/fhs.py
This PR expands existing fhs setup to make `/`  and `/opt` readonly, and make `/root` a separate dataset.
=> NAS-124338 / 24.04 / Make rootfs readonly

truenas_install/fhs.py
We need to be able to write to the path where we're mounting clusters.
=> Create cluster dataset

truenas_install/__main__.py
We now store SSH keys for admin user in /home and so we should preserve it on upgrades.
=> NAS-124479 / 24.04 / rsync home dir to new boot environment on upgrade

truenas_install/__main__.py
We now store SSH keys for admin user in /home and so we should preserve it on upgrades.
Original PR: https://github.com/truenas/scale-build/pull/504
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124479
=> NAS-124479 / 23.10.1 / rsync home dir to new boot environment on upgrade (by anodos325)

truenas_install/__main__.py
We now store SSH keys for admin user in /home and so we should preserve it on upgrades.
Original PR: https://github.com/truenas/scale-build/pull/504
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124479
=> NAS-124479 / 23.10.0 / rsync home dir to new boot environment on upgrade (by anodos325)

truenas_install/__main__.py
We now store SSH keys for admin user in /home and so we should preserve it on upgrades.
Original PR: https://github.com/truenas/scale-build/pull/504
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124479
=> NAS-124479 / 22.12.4.1 / rsync home dir to new boot environment on upgrade (by anodos325)

truenas_install/__main__.py
TrueNAS Core installs by default do not have a /home directory and so it should be omitted when copying data to new boot environment on that platform. No attempt is made to copy a non-default /home configuration because that directory is used in SCALE and may cause undesired behavior post-upgrade.
=> NAS-124646 / 24.04 / Fix upgrade path from Core to SCALE

truenas_install/__main__.py
TrueNAS Core installs by default do not have a /home directory and so it should be omitted when copying data to new boot environment on that platform. No attempt is made to copy a non-default /home configuration because that directory is used in SCALE and may cause undesired behavior post-upgrade.
Original PR: https://github.com/truenas/scale-build/pull/512
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124646
=> NAS-124646 / 23.10.1 / Fix upgrade path from Core to SCALE (by anodos325)

truenas_install/__main__.py
TrueNAS Core installs by default do not have a /home directory and so it should be omitted when copying data to new boot environment on that platform. No attempt is made to copy a non-default /home configuration because that directory is used in SCALE and may cause undesired behavior post-upgrade.
Original PR: https://github.com/truenas/scale-build/pull/512
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124646
=> NAS-124646 / 23.10.0 / Fix upgrade path from Core to SCALE (by anodos325)

scale_build/clean.py
Working on the new CI/CD infrastructure, I've had to forcefully stop running builds. Depending on when the build is interrupted, overlayfs mounts are left behind on the system.
However, when we run `make clean` this fails because the directories that are trying to be removed are backed by the mounted overlayfs mounts. We can safely ignore these errors and move on because `make packages` will clean up any left over overlay mounts for each package.
Finally, use `os.scandir` because it's more efficient and remove `os.path.exists` calls that occur before performing file I/O since that's a theoretical race condition.
=> NAS-124675 / 24.04 / Fix make clean

scale_build/clean.py
Working on the new CI/CD infrastructure, I've had to forcefully stop running builds. Depending on when the build is interrupted, overlayfs mounts are left behind on the system.
However, when we run `make clean` this fails because the directories that are trying to be removed are backed by the mounted overlayfs mounts. We can safely ignore these errors and move on because `make packages` will clean up any left over overlay mounts for each package.
Finally, use `os.scandir` because it's more efficient and remove `os.path.exists` calls that occur before performing file I/O since that's a theoretical race condition.
Original PR: https://github.com/truenas/scale-build/pull/515
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124675
=> NAS-124675 / 23.10.1 / Fix make clean (by yocalebo)

conf/build.manifest, conf/reference-files/etc/group, conf/reference-files/etc/passwd
git cherry-pick -x 21f61c6a15f741c02f9788d3289e3013f96f1bd2
git cherry-pick -x 2ac630a206e915e65cd8174edd7c27506bf3aee8
git cherry-pick -x 114b4bb0061be65c2091fd16448859f65677b5fe
This PR adds changes to not build inadyn any longer because it is no longer a service in SCALE and hence no reason to include it in the build (it was removed in https://github.com/truenas/middleware/pull/11403)
Original PR: https://github.com/truenas/scale-build/pull/519
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124677
=> NAS-124677 / 23.10.1 / We should not be building inadyn anymore (by sonicaj)

conf/build.manifest
Until we fix the issue where base chroot cache is not invalidated whenever group/passwd files are changed, let's bump build epoch to fix incrementals
=> NAS-124717 / 24.04 / Bump build epoch as group/passwd files have been changed

conf/build.manifest
Until we fix the issue where base chroot cache is not invalidated whenever group/passwd files are changed, let's bump build epoch to fix incrementals
Original PR: https://github.com/truenas/scale-build/pull/522
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124717
=> NAS-124717 / 23.10.1 / Bump build epoch as group/passwd files have been changed (by sonicaj)

scale_build/image/update.py
This cannot be done before, as it is being used to mask the `apt` executables.
(Corresponding middleware PR (#[12140](https://github.com/truenas/middleware/pull/12140)) is being held until this is merged.)
=> NAS-121831 / 24.04 / Make pkg_mgmt_disabled executable in post_rootfs_setup

conf/build.manifest
https://github.com/truenas/zfs/pull/181
=> NAS-125238 / 24.04 / Use stable/dragonfish to relax half ARC limits for dragonfish nightlies

conf/build.manifest
Upstream ZFS has automated changelog generation with new version. This commit adapts to that change and generates changelog from configure.
This PR should be merged before https://github.com/truenas/zfs/pull/183 is merged.
=> NAS-125230 / 24.04 / Update OpenZFS build to generate changelog

conf/build.manifest
Upstream ZFS has automated changelog generation with new version. This commit adapts to that change and generates changelog from configure.
This PR should be merged before https://github.com/truenas/zfs/pull/184 is merged.
=> NAS-125230 / 23.10.1 / Update OpenZFS build to generate changelog

conf/reference-files/etc/group
This is in support of users upgrading from CORE.
=> NAS-125340 / 24.04 / Add nobody group, with the same gid as nogroup.

conf/build.manifest
This reverts commit 1211f4a9f5e2d0eec66b40c984104ee015127823. The reason why this is being reverted is because I updated our local fork to pull in 7.4-2 (latest upstream at time of writing). This pulls in both of the local patches we pushed upstream but also fixes another issue that 1 of our SCALE users is experiencing. See https://github.com/truenas/smartmontools/pull/3 for details on bumping to 7.4-2.
=> NAS-125875 / 24.04 / Revert "Remove smartmontools fork" (Bump to 7.4-2 upstream)

conf/build.manifest
This reverts commit 1211f4a9f5e2d0eec66b40c984104ee015127823.
(cherry picked from commit 9df1eac2eb7e72f629fb847dcdae0093f7c55d6f)
=> NAS-125875 / 23.10.2 / Revert "Remove smartmontools fork"

scale_build/bootstrap/cache.py, scale_build/update_image.py, scale_build/utils/reference_files.py, scale_build/validate.py
In the SCALE build process, when building the cache, it considers necessary cache files. If these files already exist, the SCALE build doesn't rebuild the cache, assuming the previous cache is sufficient. However, if the user or group information in the reference file has changed, the cache is declared as healthy, and the SCALE build doesn't rebuild the cache.
This PR effectively tackles that problems and ensures the cached bootstrapdir actually reflects the reference group/passwd files and if reference files have been changed, it invalidates the cache and initiates a clean build. Earlier what would happen is that during update phase usually the image won't build as we validate at that point if the users currently existing in the chroot env actually reference the reference group/passwd …
=> NAS-125472 / 24.04 / Validate cached bootstrap directory based off on the reference group/passwd files

conf/build.manifest
This will be used to create 23.10.1.1 hotfix release. All fixes are contained to `truenas/middleware` repo.
=> NAS-125996 / 23.10.1.1 / add 23.10.1.1 build for middleware repo

conf/build.manifest
This pulls from 23.10.1.1 branch for our openssl branch to include a CVE fix as well as fix the package build.
=> bump openssl to fix build

conf/build.manifest
This is to bring in two bugfix commits related to network speed reporting into the build for quick validation ahead of the 23.10.1.1 release:
=> Add truenas/webui 23.10.1.1 release branch to 23.10.1.1 build

conf/build.manifest
SCST 3.8 was [released](https://github.com/SCST-project/scst/releases/tag/v3.8) yesterday.
We want to switch to it in 24.04 and later in order to pickup the fix for NAS-126694 which was pushed upstream first (plus other fixes from upstream).
(We will cherry-pick the change into SCST `stable/cobia` branch.)
=> NAS-126694 / 24.04 / Switch scst branch from truenas-pre-3.8.x to truenas-3.8.x

conf/build.manifest
This commit fixes a CVE affecting SSH packages
=> NAS-125785 / 24.04 / Pull ssh packages from security mirror

conf/build.manifest
As planned in https://ixsystems.atlassian.net/browse/NAS-125733. Ticket is already closed even though systemd-container is not added explicitly as a package to install. It is currently only included in SCALE as [a transient dependency of libvirt-daemon-system](https://github.com/truenas/middleware/blob/release/24.04-BETA.1/debian/debian/control). See my previous attempt at this PR for more info: https://github.com/truenas/scale-build/pull/482.
Re-targeted https://github.com/truenas/scale-build/pull/572 for the `master` branch as instructed by @kmoore134.
=> Explicitly add systemd-container to additional-packages list

conf/build.manifest
As planned in https://ixsystems.atlassian.net/browse/NAS-125733. Ticket is already closed even though systemd-container is not added explicitly as a package to install. It is currently only included in SCALE as [a transient dependency of libvirt-daemon-system](https://github.com/truenas/middleware/blob/release/24.04-BETA.1/debian/debian/control). See my previous attempt at this PR for more info: https://github.com/truenas/scale-build/pull/482.
(cherry picked from commit ab3b2304aeeafbec52ff6b24ad27689a8123fcdc)
=> NAS-127113 / 24.10 / Explicitly add systemd-container to additional-packages list

conf/build.manifest
As planned in https://ixsystems.atlassian.net/browse/NAS-125733. Ticket is already closed even though systemd-container is not added explicitly as a package to install. It is currently only included in SCALE as [a transient dependency of libvirt-daemon-system](https://github.com/truenas/middleware/blob/release/24.04-BETA.1/debian/debian/control). See my previous attempt at this PR for more info: https://github.com/truenas/scale-build/pull/482.
(cherry picked from commit ab3b2304aeeafbec52ff6b24ad27689a8123fcdc)
Original PR: https://github.com/truenas/scale-build/pull/574
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127113
=> NAS-127113 / 24.04-RC.1 / Explicitly add systemd-container to additional-packages list (by yocalebo)

truenas_install/__main__.py
We want to preserve the nvram files created by VMs so in electric eel we can migrate them over to user based pools.
Some guests don't like it if they are not preserved and they lose their UEFI boot configuration.
Solution agreed upon was based on 2 parts:
1. Saving this file on user pools which is going to happen in electric eel
2. Until electric eel - for cobia/dragonfish we preserve these files across upgrades
=> NAS-127122 / 24.10 / Preserve nvram files of vms across scale upgrades

truenas_install/__main__.py
We want to preserve the nvram files created by VMs so in electric eel we can migrate them over to user based pools.
Some guests don't like it if they are not preserved and they lose their UEFI boot configuration.
Solution agreed upon was based on 2 parts:
1. Saving this file on user pools which is going to happen in electric eel
2. Until electric eel - for cobia/dragonfish we preserve these files across upgrades
Original PR: https://github.com/truenas/scale-build/pull/576
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127122
=> NAS-127122 / 24.04-RC.1 / Preserve nvram files of vms across scale upgrades (by Qubad786)

truenas_install/__main__.py
We want to preserve the nvram files created by VMs so in electric eel we can migrate them over to user based pools.
Some guests don't like it if they are not preserved and they lose their UEFI boot configuration.
Solution agreed upon was based on 2 parts:
1. Saving this file on user pools which is going to happen in electric eel
2. Until electric eel - for cobia/dragonfish we preserve these files across upgrades
Original PR: https://github.com/truenas/scale-build/pull/576
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127122
=> NAS-127122 / 23.10.2 / Preserve nvram files of vms across scale upgrades (by Qubad786)

conf/build.manifest
This commit fixes a CVE found in glibc/libc6 by pulling it in from debian security mirror.
=> NAS-127121 / 24.10 / Address CVE-2023-6246

conf/build.manifest
Python is removing builtin `crypt` module in 3.13. To get ahead of the game, I wrote our own C bindings as a drop-in replacement.
=> NAS-124714 / 24.10 / add py-cryptit to build

scale_build/packages/build.py
Product management has asked us to add the code name on the UI side which needs to come from middleware which needs to come from this change 😄 
We already have this mostly automated but this will allow us to parse this value on middleware side.
=> NAS-127301 / 24.10 / add codename to manifest.json

scale_build/packages/build.py
Product management has asked us to add the code name on the UI side which needs to come from middleware which needs to come from this change 😄 
We already have this mostly automated but this will allow us to parse this value on middleware side.
Original PR: https://github.com/truenas/scale-build/pull/595
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127301
=> NAS-127301 / 24.04-RC.1 / add codename to manifest.json (by yocalebo)

conf/build.manifest
This is required to unbreak the build.
=> NAS-127740 / 24.10 / Pin bookworm-security for node-related packages

conf/build.manifest
This syncs up version of python-netsnmpagent with what is used in TrueNAS core, which includes many fixes (including use-after-free).
=> NAS-128069 / 24.10 / Update python-netsnmpagent library

conf/build.manifest
This works around an intermittent issue seen on lower-resourced build VMs.
---
Issue has been seen on:
- On XEN VM
- On Hyper-V VM
Did a successful build with the change [here](https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/Build%20-%20TrueNAS%20SCALE_Custom/799/)
=> NAS-128110 / 24.10 / Add increased network timeout for yarn install.

truenas_install/__main__.py
We want to copy over netdata state from older BE to new BE - this basically just contains a few KB of data which includes a UUID which netdata uses to identify itself which we want to essentially persist across upgrades.
=> NAS-127880 / 24.10 / Make sure we copy over netdata state from previous BE to new BE

truenas_install/__main__.py
git cherry-pick -x f57ba5224d255ae57ab4b0e5992b6a52766174af
git cherry-pick -x e7ce75c036df7fc0bd53c8072fef0a3df8623dd9
We want to copy over netdata state from older BE to new BE - this basically just contains a few KB of data which includes a UUID which netdata uses to identify itself which we want to essentially persist across upgrades.
Original PR: https://github.com/truenas/scale-build/pull/609
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127880
=> NAS-127880 / 24.04.0 / Make sure we copy over netdata state from previous BE to new BE (by Qubad786)

truenas_install/__main__.py
This file will be written by the installer API server https://ixsystems.atlassian.net/browse/NAS-127428 and subsequently read by the middleware to set up the network configuration (as discussed in NEP-045)
=> NAS-128355 / 24.10 / Write `/data/post-install.json`

conf/build.manifest
Looks like we need to bump epoch since the APT urls changed. Incremental jobs fail to build since the cached packages still reference the old APT urls. This seems like the only fool-proof way to clean it up.
=> NAS-128548 / 24.10 / bump epoch since apt cdn urls changed

conf/build.manifest
Looks like we need to bump epoch since the APT urls changed. Incremental jobs fail to build since the cached packages still reference the old APT urls. This seems like the only fool-proof way to clean it up.
Original PR: https://github.com/truenas/scale-build/pull/624
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128548
=> NAS-128548 / 24.04.1 / bump epoch since apt cdn urls changed (by yocalebo)

conf/build.manifest
This is unmaintained and I've confirmed that it's shipping a broken `chelsio_adapter_config.py` script which is, essentially, the entire purpose of this repo. This has been broken since SCALE has been released publicly which is why I can justify removing it from the build. I will work with platform team on a proper solution.
NOTE: the only tool we install from this repo is `cxgbtool`. Again, we don't have that on CORE and we're not using it on SCALE. This repo is too large with too much cruft to justify shipping SCALE with a tool that's not even used and shipping a script that doesn't even work.
P.S. linux has proper in-tree drivers for all the various Chelsio cards so we're losing no functionality (with the exception of `cxgbtool` (that we don't even use))
P.S.S. Making a correction. We …
=> NAS-128497 / 24.10 / remove unmaintained chelsiouwire

conf/build.manifest
Rolling to SCST tip to pickup a couple of changes we pushed upstream:
- iscsi-scst: Add mechanism to restore target parameter to default (#[232](https://github.com/SCST-project/scst/pull/232))
- iscsi-scst: Add `link_local` parameter (#[228](https://github.com/SCST-project/scst/pull/228))
=> NAS-128574 / 24.10 / Switch scst branch from truenas-3.8.x to truenas-3.9.0-pre

conf/build.manifest
This works around an intermittent issue seen on lower-resourced build VMs.
---
Issue has been seen on:
- On XEN VM
- On Hyper-V VM
Did a successful build with the change [here](https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/Build%20-%20TrueNAS%20SCALE_Custom/799/)
Original PR: https://github.com/truenas/scale-build/pull/608
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128110
=> NAS-128110 / 24.04.1 / Add increased network timeout for yarn install. (by bmeagherix)

conf/cd-files/etc/avahi/avahi-daemon.conf, conf/cd-files/etc/avahi/services/HTTP.service, conf/cd-files/etc/avahi/services/TRUENAS_INSTALLER.service, scale_build/image/iso.py
This some basic avahi configuration to the installer so that the avahi-daemon can start properly on boot and indicate the installer service is in an INIT state.
=> NAS-128746 / 24.10 / Add basic avahi configuration to ISO installer

truenas_install/__main__.py, truenas_install/fhs.py
Different subsystems in `/data/subsystems` expects that their relevant users are able to read/write data in their respective dirs i.e libvirt. However with recursively doing `700` on `/data` that is not possible which results in those subsystems breaking.
After discussing with Andrew, the best possible way forward which has been deduced is to do the following:
1. `700` on `/data` recursively ensuring everything inside has `700` perms
2. `755` on just `/data` itself
3. `755` recursively on `/data/subsystems`
This approach ensures that most of the stuff which is sensitive has correct perms in place preventing misuse and necessary directories which can/should be accessed are accessible by their respective users.
=> NAS-128714 / 24.10 / Make changes to correct perms on /data

truenas_install/__main__.py, truenas_install/fhs.py
git cherry-pick -x 9941716bb109f3bd5e6d2c40ca95da7f550eda43
git cherry-pick -x bf09f2ad93b6077c0795930a96ba11c57f38096a
Different subsystems in `/data/subsystems` expects that their relevant users are able to read/write data in their respective dirs i.e libvirt. However with recursively doing `700` on `/data` that is not possible which results in those subsystems breaking.
After discussing with Andrew, the best possible way forward which has been deduced is to do the following:
1. `700` on `/data` recursively ensuring everything inside has `700` perms
2. `755` on just `/data` itself
3. …
=> NAS-128714 / 24.04.1 / Make changes to correct perms on /data (by Qubad786)

conf/cd-files/etc/avahi/services/TRUENAS_INSTALLER.service
We decided against having mDNS update installer status since we won't be consuming the feature.
=> NAS-129131 / 24.10 / Remove TXT record from mDNS for truenas_installer

conf/build.manifest
This commit changes the truenas_webui build process so that we download the version specified in the fetch script from upstream, validate the shasum for tarball, and install in the chroot environment for the truenas_webui package build.
This ensures that the webui team can specify which nodejs version to build against without having to rely on upstream debian package.
=> NAS-129248 / 24.10 / Use pre-built nodejs for truenas_webui

scale_build/validate.py, truenas_install/__main__.py, truenas_install/dhs.py
Certain essential files and directories, such as subsystems and ZFS, are stored in the `/data` directory. Each of these files and directories must have their own specific permissions, and some of them must exist for the OS to function properly.
Define a data hierarchy to ensure that the `/data` directory follows the specified structure. If the specified hierarchy does not exist, create the necessary directories and set the relevant permissions.
=> NAS-129054 / 24.10 / Enforce data directory paths and permissions

truenas_install/__main__.py
We were incorrectly referencing path key for each entry defined in data hierarchy which led to `truenas_install` execution failing.
=> NAS-129353 / 24.10 / Correctly reference entry key

scale_build/config.py
Bump this to 24.04.3-MASTER so anyone running 24.04.2 can upgrade to the "next" release (even though, at the time of writing this, we have no plans for a 24.04.3 release).
=> NAS-129655 / 24.04.2 / bump _VERS in stable/dragonfish

scale_build/config.py, scale_build/image/iso.py, scale_build/image/manifest.py, scale_build/iso.py, truenas_install/__main__.py
If the environment variable TRUENAS_VENDOR is passed, upon ISO creation we create a /data/.vendor file that is JSON encoded, containing a "name" key with the value passed from TRUENAS_VENDOR.
=> NAS-129797 / 24.10 / Add .vendor to ISO

conf/build.manifest
c.f. https://github.com/truenas/middleware/pull/14091 for details.
=> NAS-130269 / 24.10 / remove reference to unused pcm repo

conf/build.manifest
[NAS-130356](https://ixsystems.atlassian.net/browse/NAS-130356): Adding `intel-gpu-tools` package at community request.
Passed all tests except `test_system_general_ui_rollback.test_system_general_ui_rollback`.
http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1760/
=> NAS-130356 / 24.10 / `intel-gpu-tools`

conf/build.manifest
We have replaced nslcd with SSSD.
=> NAS-130350 / 24.10 / Remove nslcd package from build

scale_build/image/update.py
[NAS-130351](https://ixsystems.atlassian.net/browse/NAS-130351): Cleaning out /var/trash package diversions.
API tests: http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1769/
=> NAS-130351 / 24.10 / clean `/var/trash`

conf/build.manifest
This was originally installed as a recommended package for nslcd, and so
it must be re-added now that nslcd is no longer included in base packages.
=> NAS-130395 / 24.10 / Add nscd to base build

conf/build.manifest
The version in bookworm-backports has our patches so we can remove this custom repo.
=> NAS-130266 / 24.10 / use smartmontools from backports

scale_build/image/manifest.py, scale_build/image/mtree.py, scale_build/image/update.py
This generates mtree of certain critical datasets used by OS such as /usr and writes it to base install to simplify process of detecting malicious or unsupported changes by third parties.
=> NAS-130445 / 24.10 / Generate mtree of some critical datasets

conf/build.manifest
This PR adds changes to bring golang from bookworm-backports because we need newer version i.e 1.22 of golang to build rclone which is not otherwise available in stable.
=> NAS-130370 / 24.10 / Bring in golang from bookworm-backports

truenas_install/__main__.py
This commit adds changes to fix upgrades when we have apps running with same processes which we check for removed services.
Original PR: https://github.com/truenas/scale-build/pull/689
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130581
=> NAS-130581 / 24.10-RC.1 / Fix upgrades when we have apps running (by sonicaj)

README.md
This commit adds changes to specify that libarchive-tools is required to build scale as we use a util which this provides i.e bsdtar in generating mtree of critical datasets.
=> NAS-130580 / 25.04 / Specify libarchive-tools is required to build SCALE

truenas_install/__main__.py
This commit adds changes to fix upgrades when we have apps running with same processes which we check for removed services.
Original PR: https://github.com/truenas/scale-build/pull/689
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130581
=> NAS-130581 / 24.10-BETA.1 / Fix upgrades when we have apps running (by sonicaj)

scale_build/config.py, scale_build/image/iso.py
Update to allow both standard and vendor ISO to be produced from a pipeline without the iso which is generated first being deleted.
=> TEN-1474 Option added to prevent deletion of ISO files during Make

truenas_install/__main__.py, truenas_install/fhs.py
The syslog-ng.persist file contains information about last read systemd journal message which will prevent duplicate audit table insertions and sending duplicate messages to remote syslog server.
This commit also switches our default to clone the audit dataset forward on upgrade.
=> NAS-130832 / 25.04 / Preserve the syslog-ng.persist file on upgrades

truenas_install/__main__.py, truenas_install/fhs.py
The syslog-ng.persist file contains information about last read systemd journal message which will prevent duplicate audit table insertions and sending duplicate messages to remote syslog server.
This commit also switches our default to clone the audit dataset forward on upgrade.
Original PR: https://github.com/truenas/scale-build/pull/701
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130832
=> NAS-130832 / 24.10-RC.1 / Preserve the syslog-ng.persist file on upgrades (by anodos325)

conf/build.manifest
git cherry-pick -x 8ac9aa7e4180e70508ee997d00d7ef1dcc06e85c
git cherry-pick -x b9d225811852688a30f335b35750a33931fb5a17
git cherry-pick -x 587c801d7751ee77a0f86db01ec8fe863be3046f
git cherry-pick -x c1bfeb2b7ec9c431b8a0df5f4558b73efe6fdf51
https://github.com/truenas/truenas_verify/pull/1
This is a reopen of the closed pr https://github.com/truenas/scale-build/pull/700
Original PR: https://github.com/truenas/scale-build/pull/705
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130590
=> NAS-130590 / 24.10-RC.1 / Create Debian package that verifies integrity of file system (by creatorcary)

truenas_install/fhs.py
grub2 installs config generation scripts under `/etc/grub.d/`. If `update-grub` cannot run those scripts, config generation fails and update-grub errors out.
We should remove `noexec` for `etc` dataset. There has been an upstream ZFS fix that enforces the correct mount options for Linux runtime. To enable that patch, we should first remove `noexec `permission for `/etc`, otherwise installation would break.
Upstream PR: https://github.com/openzfs/zfs/pull/16393
=> NAS-130821 / 24.10.0 / Remove noexec permission for /etc

truenas_install/fhs.py
During the upgrade process its possible for the syslog-ng cursor for the systemd journal to advance beyond what is present in the newly cloned logs dataset. This results in syslog-ng re-reading the same messages and sending them a second time to remote syslog servers, our audit databases, and local files.
For typical purposes the systemd journal is treated as ephemeral data, but is not something we want to lose on reboot or upgrade. This means that volatile storage is undesirable. As a compromise solution that absolutely prevents duplicate entries we have settled on creating a new dedicated systemd journal dataset on upgrades. The old journal contents dataset are preserved in the previous boot environment.
This has the added advantage of allowing us to disable ACL support on the logs …
=> NAS-131125 / 24.10-RC.1 / Do not clone systemd journal on upgrade (by anodos325)

truenas_install/fhs.py
During the upgrade process its possible for the syslog-ng cursor for the systemd journal to advance beyond what is present in the newly cloned logs dataset. This results in syslog-ng re-reading the same messages and sending them a second time to remote syslog servers, our audit databases, and local files.
For typical purposes the systemd journal is treated as ephemeral data, but is not something we want to lose on reboot or upgrade. This means that volatile storage is undesirable. As a compromise solution that absolutely prevents duplicate entries we have settled on creating a new dedicated systemd journal dataset on upgrades. The old journal contents dataset are preserved in the previous boot environment.
This has the added advantage of allowing us to disable ACL support on the logs …
=> NAS-131125 / 24.10.0 / Do not clone systemd journal on upgrade (by anodos325) (by bugclerk)

conf/build.manifest
git cherry-pick -x 8e35a07b3af063e66ca45e97aec21dd5a1406b1f
git cherry-pick -x 2f97e32b3069346445e91d6f7f44d62c2a83cecd
Original PR: https://github.com/truenas/scale-build/pull/725
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131338
=> NAS-131338 / 24.10-RC.1 / Bring in non-free firmware for debian backports (by sonicaj)

conf/build.manifest
git cherry-pick -x 8e35a07b3af063e66ca45e97aec21dd5a1406b1f
git cherry-pick -x 2f97e32b3069346445e91d6f7f44d62c2a83cecd
Original PR: https://github.com/truenas/scale-build/pull/725
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131338
=> NAS-131338 / 24.10.0 / Bring in non-free firmware for debian backports (by sonicaj)

conf/build.manifest
In https://github.com/truenas/binaries/pull/5 we manually added the missing binary firmware file to fix Intel ARC gpu transcoding. We did not, however, add this to EE because by the time we released EE the upstream package should have included this file.
What we neglected to do was prioritize the bookworm-backports repo for this package so we're pulling an ancient version (20230210-5) when the version in backports is 20240709-2~bpo12+1. Outside of this specific reason, pulling in the latest package also includes latest intel/amd64 microcode which fixes all kinds of fun things (cve, stability, performance, etc) for cpu firmware.
=> NAS-131234 / 25.04 / pull in latest firmware-linux package from bookworm backports

conf/build.manifest
In https://github.com/truenas/binaries/pull/5 we manually added the missing binary firmware file to fix Intel ARC gpu transcoding. We did not, however, add this to EE because by the time we released EE the upstream package should have included this file.
What we neglected to do was prioritize the bookworm-backports repo for this package so we're pulling an ancient version (20230210-5) when the version in backports is 20240709-2~bpo12+1. Outside of this specific reason, pulling in the latest package also includes latest intel/amd64 microcode which fixes all kinds of fun things (cve, stability, performance, etc) for cpu firmware.
Original PR: https://github.com/truenas/scale-build/pull/720
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131234
=> NAS-131234 / 24.10.0 / pull in latest firmware-linux package from bookworm backports (by yocalebo)

conf/build.manifest
In https://github.com/truenas/binaries/pull/5 we manually added the missing binary firmware file to fix Intel ARC gpu transcoding. We did not, however, add this to EE because by the time we released EE the upstream package should have included this file.
What we neglected to do was prioritize the bookworm-backports repo for this package so we're pulling an ancient version (20230210-5) when the version in backports is 20240709-2~bpo12+1. Outside of this specific reason, pulling in the latest package also includes latest intel/amd64 microcode which fixes all kinds of fun things (cve, stability, performance, etc) for cpu firmware.
Original PR: https://github.com/truenas/scale-build/pull/720
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131234
Original PR: …
=> NAS-131234 / 24.10-RC.1 / pull in latest firmware-linux package from bookworm backports (by yocalebo) (by bugclerk)

conf/build.manifest
We recently updated master apt servers which has broken the build. The libc* dependencies that come from the bookworm-security are now older than what is provided in the standard repo. The bookworm-security pulls in version 2.36-9+deb12u7. By removing these entries, the version that is pulled in is 2.36-9+deb12u8.
=> NAS-131346 / 25.04 / fix master build

conf/build.manifest
This commit adds an explicit openssl dependency for swagger as swagger brings in npm for build-depends which in turn needs libssl and friends which will error out if there is a mismatch of libssl versions (that is a separate bug ofc) but the point is that swagger depends on openssl so we should mark it as such.
=> NAS-131352 / 25.04 / Add explicit openssl dependency for swagger

truenas_install/__main__.py
I'm not even really sure how this has worked in the first place....QE has a system (running 24.04.2.2) with a Gold license that they're manually upgrading to what will be EE-RC.1. They're met with a deprecation message and the update fails. After investigation, I'm not sure how this has ever worked....
The system they had was running minio which produced a running service name of  `minio` but the crgroup entry was
```
0::/kubepods.slice/kubepods-burstable.slice/kubepods-burstable pod3c3941c1_24e7_4189_854f_f9dfcfa638ef.slice/cri-containerd-14ef8d9c8a76f8c8f1731bd455062481c4e03f683fe52566bbc4fc74f480225.scope
```
I went ahead and installed webdav app and also saw it produce an entry like so
```
0::/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podf905dab1_0a2c_4e68_9d0c_861da18 …
```
=> NAS-131449 / 25.04 / fix bug in deprecated service detection

truenas_install/__main__.py
I'm not even really sure how this has worked in the first place....QE has a system (running 24.04.2.2) with a Gold license that they're manually upgrading to what will be EE-RC.1. They're met with a deprecation message and the update fails. After investigation, I'm not sure how this has ever worked....
The system they had was running minio which produced a running service name of  `minio` but the crgroup entry was
```
0::/kubepods.slice/kubepods-burstable.slice/kubepods-burstable pod3c3941c1_24e7_4189_854f_f9dfcfa638ef.slice/cri-containerd-14ef8d9c8a76f8c8f1731bd455062481c4e03f683fe52566bbc4fc74f480225.scope
```
I went ahead and installed webdav app and also saw it produce an entry like so
```
0::/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podf905dab1_0a2c_4e68_9d0c_861da18 …
```
=> NAS-131449 / 24.10-RC.1 / fix bug in deprecated service detection (by yocalebo)

truenas_install/__main__.py
I'm not even really sure how this has worked in the first place....QE has a system (running 24.04.2.2) with a Gold license that they're manually upgrading to what will be EE-RC.1. They're met with a deprecation message and the update fails. After investigation, I'm not sure how this has ever worked....
The system they had was running minio which produced a running service name of  `minio` but the crgroup entry was
```
0::/kubepods.slice/kubepods-burstable.slice/kubepods-burstable pod3c3941c1_24e7_4189_854f_f9dfcfa638ef.slice/cri-containerd-14ef8d9c8a76f8c8f1731bd455062481c4e03f683fe52566bbc4fc74f480225.scope
```
I went ahead and installed webdav app and also saw it produce an entry like so
```
0::/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podf905dab1_0a2c_4e68_9d0c_861da18 …
```
=> NAS-131449 / 24.10.0 / fix bug in deprecated service detection (by yocalebo)

truenas_install/__main__.py
Types mismatch results in installer crashing when unsquashfs error occurs
=> NAS-131773 / 25.04 / Fix unsquashfs error reporting

truenas_install/__main__.py
Types mismatch results in installer crashing when unsquashfs error occurs 
Original PR: https://github.com/truenas/scale-build/pull/741
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131773
=> NAS-131773 / 24.10.0 / Fix unsquashfs error reporting (by themylogin)

truenas_install/__main__.py
Types mismatch results in installer crashing when unsquashfs error occurs 
Original PR: https://github.com/truenas/scale-build/pull/741
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131773
=> NAS-131773 / 24.10.1 / Fix unsquashfs error reporting (by themylogin)

conf/reference-files/etc/group, conf/reference-files/etc/passwd, truenas_install/__main__.py, truenas_install/dhs.py
After talking with Andrew, we decided to change libvirt's default uid/gid as it has a high potential for a clash with the default uid/gid in place. A uid/gid has been chosen for libvirt which is under 1000 and reduces a potential clash with a user configured uid/gid.
=> NAS-131695 / 25.04 / Change default libvirt uid/gid

conf/build.manifest
Switch to a local repository for `smartmontools` to incorporate the fixes for [NAS-131327](https://ixsystems.atlassian.net/browse/NAS-131327) and [NAS-131181](https://ixsystems.atlassian.net/browse/NAS-131181).
Scale Build: http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/701/
=> NAS-131327 / 25.04 / use smartmontools from custom repo

conf/build.manifest
Switch to a local repository for `smartmontools` to incorporate the fixes for [NAS-131327](https://ixsystems.atlassian.net/browse/NAS-131327) and [NAS-131181](https://ixsystems.atlassian.net/browse/NAS-131181).
Scale Build: http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/701/
Original PR: https://github.com/truenas/scale-build/pull/750
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131327
=> NAS-131327 / 24.10.1 / use smartmontools from custom repo (by ixhamza)

conf/build.manifest, scale_build/bootstrap/bootstrapdir.py, scale_build/bootstrap/hash.py, scale_build/config.py, scale_build/image/iso.py, scale_build/image/update.py, scale_build/utils/manifest.py
Added an option to set APT_INTERNAL_BUILD in the environment, which will toggle the builder to use the CDN Apt, or the iX Internal Apt Repo. 
Additionally, the environment variable APT_BASE_CUSTOM can be set to a URL if you wish to override both options to pull from another location at build time.
=> NAS-132446 / 25.04 / Initial add of option to use internal APT repo for builds

conf/build.manifest, scale_build/bootstrap/bootstrapdir.py, scale_build/bootstrap/hash.py, scale_build/config.py, scale_build/image/iso.py, scale_build/image/update.py, scale_build/utils/manifest.py
Added an option to set APT_INTERNAL_BUILD in the environment, which will toggle the builder to use the CDN Apt, or the iX Internal Apt Repo. 
Additionally, the environment variable APT_BASE_CUSTOM can be set to a URL if you wish to override both options to pull from another location at build time. 
Original PR: https://github.com/truenas/scale-build/pull/754
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132446
=> NAS-132446 / 24.10.1 / Initial add of option to use internal APT repo for builds (by kmoore134)

conf/build.manifest, scale_build/bootstrap/bootstrapdir.py, scale_build/bootstrap/hash.py, scale_build/config.py, scale_build/image/iso.py, scale_build/image/update.py, scale_build/utils/manifest.py
This works well enough to produce broken images. It also doesn't consider local build directory caches. We'll add this functionality in a subsequent PR but need to remove this so we don't start generating images with these ENV settings.
This reverts commit 5f95982024caf849323997cd47a257726a272838.
Original PR: https://github.com/truenas/scale-build/pull/759
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132554
=> NAS-132554 / 24.10.1 / Revert NAS-132446 (by yocalebo)

conf/build.manifest, scale_build/bootstrap/bootstrapdir.py, scale_build/bootstrap/hash.py, scale_build/config.py, scale_build/image/iso.py, scale_build/image/update.py, scale_build/utils/manifest.py
This PR continues on the work we did in https://github.com/truenas/scale-build/pull/754 but additionally it makes sure the final resulting image does not has internal apt mirrors specified as those scale installations will not be able to access iX internal apt mirrors and also it ensures that cache is invalidated if apt mirrors change i.e internal apt mirror is no longer desired for a build.
=> NAS-132571 / 25.04 / Internal apt mirror support

conf/build.manifest
Build Fangtooth nightlies with Linux 6.12 LTS.
All relevant PRs have been merged. A final build is running [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/748/console).
=> NAS-130427 / 25.04 / Update Linux kernel to 6.12 LTS

truenas_install/__main__.py
SNMP uses /var/lib/snmp to hold it's configuration, including v3 user information.
This directory should be preserved across an upgrade.
This PR adds preservation of the SNMP configuration directory during an upgrade.
This same fix is valid for backport to 24.10.2.
=> NAS-132388 / 25.04 / Save snmp config directory in upgrades

truenas_install/__main__.py
SNMP uses /var/lib/snmp to hold it's configuration, including v3 user information.
This directory should be preserved across an upgrade.
This PR adds preservation of the SNMP configuration directory during an upgrade.
This same fix is valid for backport to 24.10.2.
Original PR: https://github.com/truenas/scale-build/pull/772
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132388
=> NAS-132388 / 24.10.1 / Save snmp config directory in upgrades (by mgrimesix)

truenas_install/__main__.py
SNMP uses /var/lib/snmp to hold it's configuration, including v3 user information.
This directory should be preserved across an upgrade.
This PR adds preservation of the SNMP configuration directory during an upgrade.
This same fix is valid for backport to 24.10.2.
Original PR: https://github.com/truenas/scale-build/pull/772
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132388
=> NAS-132388 / 24.10.2 / Save snmp config directory in upgrades (by mgrimesix)

scale_build/image/manifest.py
We need to go back to SHA1 for these files because the code that does the validation is on the _running_ install of SCALE. I can leave the `sha256` changes middlewared land, but changing this needs to happen a few weeks later. (To give time for people running nightlies to have the new code.).
=> NAS-132949 / 25.04 / go back to sha1 for manifest files

conf/build.manifest, scale_build/image/mtree.py, scale_build/image/update.py
This commit adds the audit rules package to the build and adds a step in which we generate the privileged rules set based on the update file before generating mtree.
=> NAS-132964 / 25.04 / Add audit rules to build

conf/build.manifest, scale_build/packages/package.py
It's somewhat challenging to predict what packages may have subtle errors due to us having different python version that what is provided by upstream. This commit ensures that when we're building packages we always have our own python package present.
=> NAS-132966 / 25.04 / Always add python3 as an explicit dependency

conf/build.manifest
Custom python has caused nothing but problems. Let's bump epoch to force all builders in our internal CI to cleanly build.
=> NAS-132987 / 25.04 / bump epoch to force clean builds

scale_build/image/update.py
We need to strip the chroot basedir prefix and make these files have absolute paths.
=> NAS-132983 / 25.04 / Add prefix argument to privileged audit rules

requirements.txt, scale_build/utils/system.py, setup.py, truenas_install/__main__.py, truenas_install/utils.py
Similar to what was done in https://github.com/truenas/middleware/pull/15227, this removes psutil from truenas_install. The logic added in `utils.py` was copy and pasted from `utils/os.py` and `utils/mount.py` in the truenas/middleware repo.
=> NAS-133293 / 25.04 / remove psutil from truenas_install

scale_build/image/update.py
This commit copies over some required auditd plugin configuration to the base install before we calculate mtree hash.
=> NAS-133535 / 25.04 / Handle audit plugin changes

scale_build/extensions.py
The issue is not that the driver updated (as was described in 192378449afb3c4e0328b527973e5c1fb4a2e84f), the issue is that `download.nvidia.com` has dead links. Using `us.download.nvidia.com` fixes the issue.
=> NAS-133580 / 25.04 / fix nvidia driver URL

conf/build.manifest
This commit updates major samba version from 4.20 to 4.21 for TrueNAS 25.04 build.
=> NAS-133632 / 25.04 / Update Samba to 4.21

conf/build.manifest
This commit updates SCST from `truenas-3.9.0-pre` to `truenas-3.10.0-pre` (i.e. tip).
----
CI test run [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/2649/), which is exhibiting similar issues as regular recent runs.  Installed on regular hardware too.
=> NAS-133696 / 25.04 / Update scst from truenas-3.9.0-pre to truenas-3.10.0-pre

conf/build.manifest
This commit adds our custom version of nfs-utils to the base install.
Original PR: https://github.com/truenas/scale-build/pull/825
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132120
=> NAS-132120 / 25.04-RC.1 / Add nfs-utils package to base install (by anodos325)

truenas_install/fhs.py
Remove the `744` mode setting on /var/lib/incus.  We will use the Debian default: `755`
=> NAS-134219 / 25.10 / Remove 744 mode set on /var/lib/incus.  Use the Debian default of 755.

truenas_install/fhs.py
Remove the `744` mode setting on /var/lib/incus.  We will use the Debian default: `755`
Original PR: https://github.com/truenas/scale-build/pull/828
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134219
=> NAS-134219 / 25.04-RC.1 / Remove 744 mode set on /var/lib/incus.  Use the Debian default of 755. (by mgrimesix)

conf/reference-files/etc/group, conf/reference-files/etc/passwd, truenas_install/__main__.py
Legacy VM plugin is being removed from TrueNAS.
Original PR: https://github.com/truenas/scale-build/pull/823
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133958
=> NAS-133958 / 25.04-RC.1 / Remove legacy VM usages from build (by Qubad786)

conf/build.manifest
These were originally provided by the debian control file for middleware.
=> NAS-133071 / 25.04 / Add SCST-related packages to base install

scale_build/image/mtree.py
Update mtree to support cryptographic verification for STIG
-------------------------------------------------------------------
Our goal is to have zero discrepancies at install.
- Added a few files to the `delete` list and `ignore` list.  These were discovered during testing.
- Created a list of files that require `chmod`
Explanation of the files added to delete:
- `etc/audit/rules.d/audit.rules`  is not used by TrueNAS.  This file is deleted by the audit subsystem.
- `etc/rc[2345].d/K01ssh` are symlinks used by the legacy init.d.  The systemd subsystem deletes these on ssh start.
=> NAS-133968 / 25.10 / Update mtree to better support cryptographic verification for STIG

scale_build/image/mtree.py
Update mtree to support cryptographic verification for STIG
-------------------------------------------------------------------
Our goal is to have zero discrepancies at install.
- Added a few files to the `delete` list and `ignore` list.  These were discovered during testing.
- Created a list of files that require `chmod`
Explanation of the files added to delete:
- `etc/audit/rules.d/audit.rules`  is not used by TrueNAS.  This file is deleted by the audit subsystem.
- `etc/rc[2345].d/K01ssh` are symlinks used by the legacy init.d.  The systemd subsystem deletes these on ssh start.
Original PR: https://github.com/truenas/scale-build/pull/824
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133968
=> NAS-133968 / 25.04-RC.1 / Update mtree to better support cryptographic verification for STIG (by mgrimesix)

scale_build/config.py, scale_build/utils/manifest.py
This commit will allow to specify secret env which a package during build might require using environment variables (we support a dedicated `secrets.yaml` file already for this).
i.e
```
env SECRET_SENTRY_AUTH_TOKEN="SOME_TOKEN" make packages PACKAGES="truenas_webui"
```
=> NAS-135571 / 25.10 / Allow specifying secret_env for packages as env variables

.github/workflows/manifest.yml, truenas_install/__main__.py
This commit adds a basic python version check to the truenas_install module so that we can raise a useful error message if someone is somehow running the installer in the context of a really old python version (like in 13).
=> NAS-135854 / 25.10 / Add python version check to truenas_install module

.github/workflows/manifest.yml, truenas_install/__main__.py
This commit adds a basic python version check to the truenas_install module so that we can raise a useful error message if someone is somehow running the installer in the context of a really old python version (like in 13).
Original PR: https://github.com/truenas/scale-build/pull/857
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135854
=> NAS-135854 / 25.04.2 / Add python version check to truenas_install module (by anodos325)

.github/workflows/manifest.yml, truenas_install/__main__.py
This commit adds a basic python version check to the truenas_install module so that we can raise a useful error message if someone is somehow running the installer in the context of a really old python version (like in 13).
Original PR: https://github.com/truenas/scale-build/pull/857
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135854
=> NAS-135854 / 25.04.1 / Add python version check to truenas_install module (by anodos325)

conf/build.manifest
Nothing is using this (yet) but adding this now makes it for easier development moving forward. Related PR: https://github.com/truenas/truenas_pylibzfs/pull/59
=> NAS-135905 / 25.10 / add truenas_pylibzfs to build

truenas_install/__main__.py
A typo in the code prevented cloning the necessary datasets during upgrades.
This effected syslog, audit.log and all logs that relied on the clone.
**Before upgrade. Note the timestamps for comparison**
---------------------------------------
```
root@upgrade-testing[~]# cat /etc/version
25.04.0
root@upgrade-testing[~]# head /var/log/syslog
Jun  6 15:21:51 truenas syslog-ng[2008]: syslog-ng starting up; version='3.38.1'
Jun  6 08:07:26 truenas kernel: Linux version 6.12.15-production+truenas (root@tnsbuilds01.tn.ixsystems.net)
Jun  6 08:07:26 truenas kernel: Command line: BOOT_IMAGE=/ROOT/25.04.0@/boot/vmlinuz-6.12.15-production+truenas 
root@upgrade-testing[~]#
root@upgrade-testing[~]# head /var/log/audit/audit.log
type=DAEMON_START msg=audit(1749248066.077:1771): op=start ver=3.0.9 …
```
=> NAS-136140 / 25.10 / Maintain logs across upgrades

truenas_install/__main__.py
A typo in the code prevented cloning the necessary datasets during upgrades.
This effected syslog, audit.log and all logs that relied on the clone.
**Before upgrade. Note the timestamps for comparison**
---------------------------------------
```
root@upgrade-testing[~]# cat /etc/version
25.04.0
root@upgrade-testing[~]# head /var/log/syslog
Jun  6 15:21:51 truenas syslog-ng[2008]: syslog-ng starting up; version='3.38.1'
Jun  6 08:07:26 truenas kernel: Linux version 6.12.15-production+truenas (root@tnsbuilds01.tn.ixsystems.net)
Jun  6 08:07:26 truenas kernel: Command line: BOOT_IMAGE=/ROOT/25.04.0@/boot/vmlinuz-6.12.15-production+truenas 
root@upgrade-testing[~]#
root@upgrade-testing[~]# head /var/log/audit/audit.log
type=DAEMON_START msg=audit(1749248066.077:1771): op=start ver=3.0.9 …
```
=> NAS-136140 / 25.04.2 / Maintain logs across upgrades (by mgrimesix)

jenkins/Publish-ISO
In support of feature [Update Trains Tagging](https://ixsystems.atlassian.net/browse/NAS-133600)
This change adds a releases.json file with one entry per release on push of the update file, based on the manifest information for that release. The releases.json file will be kept limited to 30 packages.
=> TEN-2441 Addition of releases.json file for nightly builds

truenas_install/__main__.py
We added some changes which made sure smartd was not being started on boot automatically and respects user setting. This was being respected on upgrade, however on fresh install in FT - smart according to database is to set automatically but that is not being reflected in the BE.
Ensure smartmontools service is enabled during fresh installation to match the database state.
=> NAS-136424 / 25.04.2 / Enable smartmontools service on fresh install

conf/build.manifest
This commit switches SCALE from being built with Samba 4.21 to Samba 4.22.
https://wiki.samba.org/index.php/Samba_4.22_Features_added/changed
=> NAS-136455 / 25.10 / Bring in Samba 4.22

truenas_install/__main__.py
This PR adds changes to send a final event which notifies that installation or upgrade completed successfully - the last event scale build currently sends out is 96%, this is required for TNC to properly get notified via events about progress on the installation job.
=> NAS-136593 / 25.10 / Send a final event to notify that upgrade/installation completed

jenkins/Full-NoPublish, jenkins/Incremental-NoPublish, scale_build/config.py
This will change it so that the internal server that builds the nightly images and publishes them for the public, will default to non-experimental builds instead.
=> NAS-136807 / 25.10 / Fix experimental builds

conf/build.manifest
This bumps nfs-utils from 2.6 -> 2.8 and brings in many changes and fixes.
* Fix for hostnames for HA failover
* Added mTLS support
This change will not be backported to GE.
=> NAS-137222 / 26.04 / Bump nfs-utils to version from debian trixie

scale_build/image/mtree.py
We are not excluding libvirt files from mtree generation which results in audit check failing.
We should exclude libvirt configurational files from mtree generation so we don't validate it as it will result in audit check failing otherwise.
Original PR: https://github.com/truenas/scale-build/pull/908
=> NAS-137250 / 25.10-RC.1 / Remove libvirt configuration files from mtree (by Qubad786)

conf/build.manifest
This commit adds a library to handle our pwenc plugin functionality. This ensures we're using FIPS-validated crypto module for pwenc and provides a common library for a WIP PAM module.
=> NAS-137541 / 26.04 / Add truenas-pwenc to build

truenas_install/__main__.py
It seems that on some kernels/environments /sys/firmware/efi/efivars is mounted automatically with sysfs, and on some not. Specifically, `efivarfs already mounted on ...` error was raised when upgrading from 25.10. Ignoring that error helped to perform the upgrade successfully.
=> NAS-137645 / 26.04 / Fix updating from 25.10

conf/build.manifest
This replaces our custom package at https://github.com/truenas/restic and upgrades to restic 0.18.0.
=> NAS-137634 / 26.04 / Install restic from Debian

conf/build.manifest
This commit adds a library that implements RFC-5802 to our base build in preparation for adding a new truenas PAM module for implementing replay-resistant authentication.
=> NAS-137690 / 26.04 / Add truenas_scram library to build

scale_build/image/mtree.py
In a recent middleware PR (#[17193](https://github.com/truenas/middleware/pull/17193)) `dhcpcd.conf.mako` was added, therefore we should no longer check it.
=> NAS-137831 / 26.04 / Remove /etc/dhcpcd.conf from mtree
