truenas_install/__main__.py
To give some context, when we create a new BE, the specified defaults we have set for services are to disable them and a new BE has the vendor configured settings ( the preset file we ship ) being applied. So any services which the user had enabled in his old BE won't boot in the newer BE as this is remembered by systemd which is entirely replaced in the newer BE.
In this case we need to enable the services user had explicitly marked as enabled in the new BE so when the user boots, he/she has those services running.
=> Enable user enabled services when user updates

conf/build.manifest
For performance team: NAS-107902
=> add turbostat command via the linux-cpupower apt package on SCALE

conf/build.manifest
virtualized inside Azure
https://packages.debian.org/bullseye/waagent
=> NAS-108003 / 20.12 / Add "waagent", helper agent which improves support when running SCALE

conf/build.manifest
* Fixes our ability to use release engineering scripts for tag/build.
=> Switch to truenas org for sedutil

truenas_install/__main__.py
When paired with https://github.com/truenas/truenas-installer/pull/24, installation should work on virtually all block devices. I have confirmed functionality by installing on an emmc drive.
=> NAS-108649 / 21.02 / nvme/mmc compatibility: look for partitions before using

conf/build.manifest
Build issue with builtin libevent fixed in netatalk port.
=> re-enable netatalk

conf/build.manifest
https://download.samba.org/pub/samba/rc/samba-4.14.0rc1.WHATSNEW.txt
=> Build SCALE with Samba 4.14

README.md, conf/build.manifest, scripts/build.sh, scripts/functions.sh
To make my OCD happy, converted the build.manifest file over to YAML, which is much more appropriate for a build configuration, since its able to support comments (which I added a bunch of to the config file)
=> Convert to yaml

conf/build.manifest, scripts/build.sh, truenas_install/__main__.py
Reverts truenas/scale-build#126
=> Revert "NAS-107508 / 21.04 / Use grub2 from custom repo"

conf/build.manifest, scripts/build.sh, truenas_install/__main__.py
Reverts truenas/scale-build#133
=> Revert "Revert "NAS-107508 / 21.04 / Use grub2 from custom repo""

conf/build.manifest
=> NAS-110493 / 21.06 / Add traceroute

README.md
Without pip and venv we don't get very far.
=> Document new Python build dependencies

truenas_install/__main__.py
This commit fixes 2 issues, it makes sure that systems running same scale version have different machine-ids as that's what is being used by linux to determine unique mac addresses for virtual interfaces. Secondly it makes sure that on upgrades machine-id persists so that the kernel considers it to be the same machine after an upgrade.
=> NAS-110494 / 21.06 / Make sure machine-id is unique for different scale systems

conf/build.manifest
This package includes a number of ebpf tracing tools that are useful
for debugging issues in development or in production.
=> NAS-111703 / 21.08 / Add bpfcc-tools

jenkins/Full-NoPublish, jenkins/FullBuild, jenkins/Incremental-NoPublish, jenkins/Incremental-Publish, jenkins/IncrementalBuild, jenkins/Publish
I also took time to fix spaces in all jenkins piplines
=> DOCS-2458 / Added code to artifacts debug packages in all build piplines

conf/build.manifest
This builds with customized avahi-daemon from Core that
includes extended static configuration options for services
that permit specifying interface index on which to advertise.
=> NAS-113518 / 22.02-RC.2 / Build with custom avahi-daemon

truenas_install/__main__.py
This commit adds changes to enable walinuxagent in the new BE if system in question currently is azure.
=> NAS-113649 / 22.02 / Enable walinuxagent as required on upgrades

scale_build/image/update.py
This commit adds changes to make apt binaries non-executable to make it harder for people to footshoot themselves by installing packages or removing them.
=> NAS-114025 / 22.02 / Make apt binaries non-executable

conf/cd-files/root/.bash_profile
Reverts truenas/scale-build#216
=> Revert "Revert "Proper way to mount boot media""

conf/build.manifest
ganesha and py-bonjour are no longer used.
=> NAS-114569 / 22.02 / Remove unused packages

conf/build.manifest
This module adds support persistent reservations for nvme devices.
=> NAS-114929 / 22.02.1 / add py-nvme to build

conf/build.manifest, conf/sources.list
Mirrors haven't been updated yet as we are blocked by IT on it. We will update mirrors once the IT issues have been addressed.
=> NAS-115932 / 22.02.1 / Branch out for 22.02.1

conf/build.manifest
git cherry-pick -x f5173d8bcf91b62c77e7b5d41de2cd320885b1f6
Original PR: https://github.com/truenas/scale-build/pull/286
Jira URL: https://jira.ixsystems.com/browse/NAS-113866
=> NAS-113866 / 22.02.2 / `truenas-devel` metapackage (by themylogin)

conf/build.manifest
git cherry-pick -x d21228ee98008418d167cfe433874c63d95376df
Original PR: https://github.com/truenas/scale-build/pull/301
Jira URL: https://jira.ixsystems.com/browse/NAS-116225
=> NAS-116225 / 22.02.2 / Use custom `smartmontools` (by themylogin)

truenas_install/__main__.py
…helper script
Original PR: https://github.com/truenas/scale-build/pull/357
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119071
=> NAS-119071 / 22.12 / Set authentication method using truenas-set-authentication-method.py … (by themylogin)

truenas_install/__main__.py
…helper script
Original PR: https://github.com/truenas/scale-build/pull/357
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119071
Original PR: https://github.com/truenas/scale-build/pull/361
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119071
=> NAS-119071 / 22.12.1 / Set authentication method using truenas-set-authentication-method.py … (by themylogin) (by bugclerk)

CODEOWNERS
=> NAS-119821 / 23.10 / remove CODEOWNERS file

conf/reference-files/etc/group
i2c-tools creates a new local user `i2c`.
=> NAS-121239 / 23.10 / fix build

conf/build.manifest, scale_build/branch_out.py, scale_build/checkout.py, scale_build/packages/package.py, scale_build/utils/manifest.py, scale_build/utils/package.py
This PR adds changes to make sure we don't clone a single repo multiple times just because it hosts more then 1 package i.e truenas/middleware.
=> NAS-117638 / 23.10 / Do not clone same repository when single repo hosts multiple packages

scale_build/image/update.py
We already remove the execute bit on the apt* related binaries, but those are simply a wrapper around dpkg. We need to remove execute bit on dpkg since it is the binary that's actually responsible for installing the binary.
=> NAS-121741 / 23.10 / remove execute bit on dpkg binary

truenas_install/__main__.py
Python modules imported within the truenas-initrd.py script may link against libs that are only present in the squashfs dir and so we should make ld aware of the usr/lib dir within it since we're not chrooted.
=> NAS-122119 / use LD_LIBRARY_PATH when installing / upgrading

truenas_install/__main__.py
…isting CORE installation
Original PR: https://github.com/truenas/scale-build/pull/441
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122255
=> NAS-122255 / 22.12.3 / Allow installing SCALE on CORE-created boot pool without upgrading ex… (by themylogin)

truenas_install/__main__.py
…isting CORE installation
Original PR: https://github.com/truenas/scale-build/pull/441
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122255
=> NAS-122255 / 23.10 / Allow installing SCALE on CORE-created boot pool without upgrading ex… (by themylogin)

conf/build.manifest
git cherry-pick -x 3a206bc5249bb589992399972633e0d5c70a36bf
git cherry-pick -x ef99f21a183075bc6aec33b538c2ac8cc19e209f
Original PR: https://github.com/truenas/scale-build/pull/446
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122389
=> NAS-122389 / 22.12.4 / Use pull script for building openseachest (by sonicaj)

conf/build.manifest
This plugin provides python bindings for sg_ses.
=> NAS-119900 / 23.10 / Add py-sg3 to build

conf/build.manifest
This fixes the installation of the root packages during build process.
=> NAS-122517 / 23.10 / fix the build

conf/build.manifest
Testing by Jenkins Scale builder: https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/Build%20-%20TrueNAS%20SCALE_Custom/475/
=> NAS-122578 / 23.10 / Switch openzfs branch to truenas/zfs-2.2-release

conf/build.manifest
Remove gnupg (and friends) to remove exposure to CVE-2022-3019
=> NAS-123031 / 23.10 / fix CVE-2022-3019

scale_build/branch_out.py
This PR adds changes to checkout and push scale build repo stable branch as well which is specified when doing the branching process for all other repos.
=> NAS-123340 / 24.04 / Refine branchout process

truenas_install/__main__.py
… under kubernetes
Original PR: https://github.com/truenas/scale-build/pull/477
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123349
=> NAS-123349 / 23.10 / Accomodate all cgroups versions when checking if a process is running… (by themylogin)

truenas_install/fhs.py
=> NAS-124127 / 24.04 / Set setuid=on for /usr dataset

conf/build.manifest
To be used to build 23.10.0.1 hot-fix release. Only brings in 4 fixes.
- 3 from middleware repo
- 1 from py-nvme repo
=> NAS-124916 / 23.10.0.1 / update build.manifest for 23.10.0.1

truenas_install/__main__.py
=> NAS-125330 / 24.04 / Restore progress reporting accidentally removed by e29b5d5b1cd93dc8d95ed0134777897b53a84257

truenas_install/__main__.py
.
Original PR: https://github.com/truenas/scale-build/pull/533
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125330
=> NAS-125330 / 23.10.1 / Restore progress reporting accidentally removed by e29b5d5b1cd93dc8d95ed0134777897b53a84257 (by themylogin)

conf/build.manifest
This pulls in a fix from the ixdiagnose repo for 23.10.1.1 hot fix release.
=> add 23.10.1.1 to ixdiagnose

scale_build/bootstrap/bootstrapdir.py
A stop gap solution has been implemented for now to fix incrementals not working.
=> NAS-126704 / 24.04 / Fix incrementals

jenkins/Publish-ISO
Updated pipeline to use the build from the dragonfish nightly.
=> TE-1394 Updates for Dragonfish pipeline creation

jenkins/FullBuild, jenkins/IncrementalBuild, jenkins/Publish-ISO, jenkins/Publish-Update
Updated to master for electric eeel.
=> TE-1934 Electric Eel updates

conf/build.manifest
Jira Ticket: https://ixsystems.atlassian.net/browse/NAS-127611
=> NAS-127611 / 24.10 / Use early truenas/zfs-2.3-release for 24.10 nightlies

conf/cd-files/root/.bash_profile
Reverts truenas/scale-build#610 due to https://github.com/truenas/truenas-installer/pull/75
=> Revert "NAS-128182 / 24.10 / Only run installer on tty"

scripts/gitlog.py
Add a script for use by new jenkins instance.
=> NAS-128572 / 24.10 / Add gitlog

scripts/gitlog.py
Add a script for use by new jenkins instance.
Original PR: https://github.com/truenas/scale-build/pull/620
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128572
=> NAS-128572 / 24.04.1 / Add gitlog (by bmeagherix)

conf/build.manifest, conf/reference-files/etc/group, conf/reference-files/etc/passwd
This adds our sssd repository to the build.
=> NAS-128564 / 24.10 / Add truenas/sssd to SCALE build

conf/build.manifest
This commit builds a freeipa client package based on our Samba and SSSD versions.
=> NAS-129202 / 24.10 / Add ipaclient package

truenas_install/dhs.py
This enforces that our /data/sentinels/ directory has 700 permissions
=> NAS-129731 / 24.10 / Enforce /data/sentinels permissions

truenas_install/__main__.py, truenas_install/fhs.py
We need to explicitly specify to create with posixacl.
=> NAS-129991 / 24.10 / Fix setting posixacl on logs dataset

truenas_install/__main__.py, truenas_install/fhs.py
We need to explicitly specify to create with posixacl.
=> NAS-129991 / 24.04.3 / Fix setting posixacl on logs dataset (#663)

scale_build/image/iso.py, scripts/grub.cfg
This injects the vendor name into our grub.cfg for the installer grub entries
=> NAS-130002 / 24.10 / Show vendor name during install

conf/build.manifest
https://www.samba.org/samba/history/samba-4.20.0.html
=> NAS-130165 / 24.10 / Update build to use Samba 4.20

conf/build.manifest, scale_build/packages/git.py, scale_build/utils/manifest.py
git cherry-pick -x e086115cf4285328ad78ab278178d660b87dc993
git cherry-pick -x d03f1da363e19232bd67e2b45b410c0ae0044b4c
git cherry-pick -x faea31157db363659a9f635f116d519dd2523318
git cherry-pick -x 684b4cd932809586e180d530b483e1a023067180
git cherry-pick -x 06bb381a91f93c077225e0661677033d4f35e94b
git cherry-pick -x b6308dc644057318dccff0df1370f1e9aeb8c17a
Original PR: https://github.com/truenas/scale-build/pull/683
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130342
=> NAS-130342 / 24.10-RC.1 / Remove nvidia drivers (by themylogin)

conf/build.manifest, scale_build/packages/git.py, scale_build/utils/manifest.py
git cherry-pick -x 91d9546f05cd1e1557345d662ab893a21b8bdf3a
git cherry-pick -x d04703743776c689755fce7b3ea42cbedff8d4dc
git cherry-pick -x 843c871d297dbbb828f5b74b020ff6b5c241bcd9
git cherry-pick -x 6b01e8a764629867e5e407098f612c361e8a52e2
git cherry-pick -x a069042f5c5b610dfe0b0c58aa2c2d1832f0472a
Original PR: https://github.com/truenas/scale-build/pull/686
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130342
=> NAS-130342 / 24.10-BETA.1 / Remove nvidia drivers (by themylogin) (by bugclerk)

truenas_install/__main__.py
This commit adds changes to fix upgrades when we have apps running with same processes which we check for removed services.
=> NAS-130581 / 25.04 / Fix upgrades when we have apps running

conf/build.manifest
https://github.com/truenas/truenas_verify/pull/1
This is a reopen of the closed pr https://github.com/truenas/scale-build/pull/700
=> NAS-130590 / 25.04 / Create Debian package that verifies integrity of file system

conf/build.manifest
This isn't confusing or anything :melting_face:
=> NAS-131247 / 25.04 / fix code_name for fangtooth

conf/build.manifest
http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/505/
=> NAS-131306 / 25.04 / Add 7zip to build

conf/build.manifest
http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/505/
Original PR: https://github.com/truenas/scale-build/pull/722
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131306
=> NAS-131306 / 24.10-RC.1 / Add 7zip to build (by creatorcary)

conf/build.manifest
http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/505/
Original PR: https://github.com/truenas/scale-build/pull/722
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131306
=> NAS-131306 / 24.10.0 / Add 7zip to build (by creatorcary)

scale_build/tests/unit/test_package_rebuild_logic.py
https://github.com/openzfs/zfs/commit/277a124 updated libzfs version prior to zfs-2.3 release.
Jira Ticket: https://ixsystems.atlassian.net/browse/NAS-131707.
Scale Build: http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/606/
API Test Run: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1275/
=> Update libzfs and libzpool version

Makefile, conf/build.manifest, scale_build/extensions.py, scale_build/image/bootstrap.py, scale_build/image/manifest.py, scale_build/image/update.py, scale_build/image/utils.py, scale_build/main.py, scale_build/utils/kernel.py, scale_build/utils/manifest.py
git cherry-pick -x 459af8155155008e18eec269570090bd77e66222
git cherry-pick -x 1e57ff583be26cc2ebec9925d898c05cbfa6ae46
Original PR: https://github.com/truenas/scale-build/pull/762
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132596
=> NAS-132596 / 24.10.2 / Move nvidia extension to the rootfs image (by themylogin)

scale_build/image/iso.py, scale_build/image/manifest.py, scale_build/image/mtree.py
Cf. https://github.com/truenas/middleware/pull/15147
=> NAS-132942 / 25.04 / use hashlib instead of subprocess

scale_build/config.py
Bump the stable/electriceel version to 24.10.3-MASTER
=> NAS-133530 / 24.10.2 / bump version to 24.10.3-MASTER

conf/build.manifest
See https://github.com/truenas/utils-linux/pull/1.
**Testing**
[Tested with SCALE build](http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/842/) to confirm that it resolves [NAS-130825](https://ixsystems.atlassian.net/browse/NAS-130825).
=> NAS-130825 / 25.04 / util-linux: switch to a local repo

conf/build.manifest
(cherry picked from commit 06e1f6287f25c5239abc0db213067501d746d84e) This changes the `stable/fangtooth` branch to checkout the stable/fangtooth repos.
=> create stable/fangtooth (#813)

conf/build.manifest
https://forums.truenas.com/t/please-add-lsusb-all-ls-commands-to-scale/9099
=> NAS-133889 / 25.10 / Add usbutils

conf/build.manifest
https://forums.truenas.com/t/please-add-lsusb-all-ls-commands-to-scale/9099
Original PR: https://github.com/truenas/scale-build/pull/812
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133889
=> NAS-133889 / 25.04-RC.1 / Add usbutils (by william-gr)

conf/build.manifest
This commit adds our custom version of nfs-utils to the base install.
=> NAS-132120 / 25.10 / Add nfs-utils package to base install

conf/reference-files/etc/group, conf/reference-files/etc/passwd, truenas_install/__main__.py
Legacy VM plugin is being removed from TrueNAS.
=> NAS-133958 / 25.10 / Remove legacy VM usages from build

conf/build.manifest
This PR adds crypto utils repo to scale build.
=> NAS-134872 / 25.10 / Add truenas_crypto_utils to build

truenas_install/__main__.py
Currently what happens is that when scale is installed, we have grub binary present in ESP of boot pool disks. Now when system starts, that grub binary is loaded and then it loads complete grub configuration from `boot-pool/grub` dataset. Now if scale system is being upgraded, and the new boot environment has a newer version of grub - it means that the grub configuration can have modules perhaps which the older binary doesn't support. Ideally this should not be the case as if there is a breaking change within grub itself, it seems a major version of grub is required. However we saw in one system that it would not load because the grub binary was old i.e 2.6 and the configuration was of 2.12 and it only worked when the binary was replaced with 2.12. 
So after discussion with Ameer, what we …
=> NAS-135783 / 25.10 / Make sure grub binary is updated on ESP if grub version changed

scale_build/update_image.py, scale_build/utils/reference_files.py
Follows from https://github.com/truenas/middleware/pull/16474
Pending test build http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/1124/
=> NAS-136064 / 25.10 / Allow default home directory to be changed when verifying build

conf/build.manifest
Add `truenas_spdk` to the build.
----
Custom build [here](http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/1134/) (incl [CI](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/4631/))
=> NAS-135917 / 25.10 / Add truenas_spdk

conf/reference-files/etc/group, conf/reference-files/etc/passwd, truenas_install/__main__.py
This reverts commit 7e91fb8bb6a58f039f492f71fcd9ac44f9f7d2f3.
=> NAS-136421 / 25.04.2 / Revert "Remove legacy VM usages from build"

conf/reference-files/etc/group, conf/reference-files/etc/passwd, truenas_install/__main__.py
This reverts commit 7e91fb8bb6a58f039f492f71fcd9ac44f9f7d2f3.
Original PR: https://github.com/truenas/scale-build/pull/878
=> NAS-136421 / 25.10 / Revert "Remove legacy VM usages from build" (by Qubad786)

truenas_install/__main__.py
This fixes a regression introduced in b648727 where users who previously migrated from Core would experience upgrade failures due to missing BIOS partition on their boot disk. The installer now checks for BIOS boot partition existence before attempting BIOS GRUB installation, preventing failures on systems without a dedicated BIOS partition. Additionally, EFI partition detection is now dynamic, checking both position 2 when BIOS partition is present and position 1 when BIOS partition is absent, rather than assuming EFI is always at position 2, ensuring proper EFI GRUB installation regardless of partition layout.
- **Core Migration:** 13.0-U6.8 → 24.04 → 24.10 → 25.04 → [25.10 Custom SCALE Build](http://jenkins.eng.ixsystems.net:8080/job/goldeye/job/custom/3/) → [26.04 Custom Scale …
=> NAS-137350 / 26.04 / Fix GRUB upgrade for systems missing BIOS partition with variable EFI

truenas_install/__main__.py
This fixes a regression introduced in b648727 where users who previously migrated from Core would experience upgrade failures due to missing BIOS partition on their boot disk. The installer now checks for BIOS boot partition existence before attempting BIOS GRUB installation, preventing failures on systems without a dedicated BIOS partition. Additionally, EFI partition detection is now dynamic, checking both position 2 when BIOS partition is present and position 1 when BIOS partition is absent, rather than assuming EFI is always at position 2, ensuring proper EFI GRUB installation regardless of partition layout.
- **Core Migration:** 13.0-U6.8 → 24.04 → 24.10 → 25.04 → [25.10 Custom SCALE Build](http://jenkins.eng.ixsystems.net:8080/job/goldeye/job/custom/3/) → [26.04 Custom Scale …
=> NAS-137350 / 25.10-RC.1 / Fix GRUB upgrade for systems missing BIOS partition with variable EFI (by ixhamza)
